'use strict';
(()=>{
const KEY='afterhours.progress.v1', app=document.getElementById('app'), modal=document.getElementById('modal');
const C=window.COURSE, byId=new Map(C.lessons.map(l=>[l.id,l]));
const paths={conversation:'M21 11a9 9 0 0 1-9 9H6l-4 3 1-6a9 9 0 1 1 18-6Z',album:'M5 3h13a2 2 0 0 1 2 2v16H7a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3 M4 18h16 M8 7h8v7H8V7Z M8 12l3-3 5 5',episodes:'M7 3h10 M5 6h14 M5 9h14a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2Z M10 12l5 3-5 3v-6Z',practice:'M20 5v5h-5 M4 19v-5h5 M4.6 9a8 8 0 0 1 13.1-3.1L20 8 M4 16l2.3 2.1A8 8 0 0 0 19.4 15',person:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z M5 21v-2a7 7 0 0 1 14 0v2H5Z',gear:'M9.5 3h5l.6 2.5 2 1.2 2.5-.7 2.5 4.3-1.9 1.7v2.3l1.9 1.7-2.5 4.3-2.5-.7-2 1.2-.6 2.2h-5L8.9 20l-2-1.2-2.5.7L1.9 15l1.9-1.7V11L1.9 9.3 4.4 5l2.5.7 2-1.2L9.5 3Z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',play:'M8 5l11 7-11 7V5Z',repeat:'M20 7v5h-5 M4 17v-5h5 M6 7a7 7 0 0 1 12-1l2 2 M18 17a7 7 0 0 1-12 1l-2-2',arrow:'M5 12h14 M13 6l6 6-6 6',back:'M19 12H5 M11 6l-6 6 6 6',chevron:'M9 5l7 7-7 7',check:'M5 12l4 4L19 6',close:'M6 6l12 12 M18 6L6 18',volume:'M11 5L6 9H3v6h3l5 4V5Z M15 8a6 6 0 0 1 0 8 M18 5a10 10 0 0 1 0 14',book:'M12 5v16 M12 5c-3-3-7-2-10-1v15c4-2 7-1 10 2 3-3 6-4 10-2V4c-3-1-7-2-10 1Z',star:'M12 3l3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1 3-6Z',moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z',flame:'M12 3c1 5 7 7 7 12a7 7 0 0 1-14 0c0-3 2-5 4-7 0 3 1 4 2 5 2-3 2-6 1-10Z',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z',award:'M12 3a6 6 0 1 0 0 12 6 6 0 0 0 0-12Z M8 14l-2 8 6-3 6 3-2-8',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',upload:'M12 16V4 M7 9l5-5 5 5 M4 16v5h16v-5',info:'M12 11v6 M12 7v.1 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',lock:'M6 10h12v11H6V10Z M8 10V6a4 4 0 0 1 8 0v4',edit:'M15 4l5 5 M3 21l5-1L21 7l-4-4L4 16l-1 5Z',headphones:'M3 14v-3a9 9 0 0 1 18 0v3 M3 13h4v8H3v-8Z M17 13h4v8h-4v-8Z'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.star}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=(l,i)=>`${l.id}:${i}`;
const fresh=()=>({version:1,name:'Никита',seedXP:65,awards:{},completed:{},active:null,activity:{},mistakes:{},journal:{},practiceDone:{},plushAssignments:{},achievementDates:{},practiceActive:null,drill:null,drillHistory:{},drillLast:null,settings:{motion:true,sound:false,speed:.85,goal:10,start:'v1-17'},created:new Date().toISOString()});
let state=fresh(),storageOK=true, routeToken=0, session=null, toastTimer, speaking=false;
const transfer=window.installTransferPractice({app,icon,esc,modal,openModal,toast,save,state:()=>state,course:C,matches,speak,stopSpeech,image:l=>image(l),today});
const learning=window.installLearning({app,icon,esc,modal,openModal,toast,save,state:()=>state,course:C,matches,speak,stopSpeech,image:l=>image(l),today});
function validate(x){
 if(!x||x.version!==1||typeof x.name!=='string'||x.name.length>40)throw Error('Некорректный формат резервной копии');
 const r=fresh();r.name=x.name.trim()||'Никита';r.seedXP=x.seedXP===65?65:0;
 for(const [k,v] of Object.entries(x.awards||{})){const [id,i]=k.split(':');const l=byId.get(id),t=l?.tasks[Number(i)];if(t&&Number.isInteger(v)&&v>=0&&v<=t.xp)r.awards[k]=v;}
 for(const [id,v] of Object.entries(x.completed||{})){if(byId.has(id)&&v&&Number.isFinite(v.errors)&&v.errors>=0&&v.errors<500&&typeof v.at==='string')r.completed[id]={at:v.at,errors:v.errors,earned:Number(v.earned)||0,guidedDone:v.guidedDone===true,day:/^\d{4}-\d{2}-\d{2}$/.test(v.day||'')?v.day:localDay(v.at)};}
 for(const [day,v] of Object.entries(x.activity||{}))if(validCalendarDay(day)&&Number.isInteger(v)&&v>=0&&v<10000)r.activity[day]=v;
 for(const [k,v] of Object.entries(x.mistakes||{})){const [id,i]=k.split(':');if(byId.get(id)?.tasks[Number(i)]&&v&&Number.isInteger(v.count)&&v.count>0)r.mistakes[k]={count:Math.min(999,v.count),due:Number(v.due)||0};}
 if(x.active&&byId.has(x.active.lesson)&&Number.isInteger(x.active.index)&&x.active.index>=0&&x.active.index<byId.get(x.active.lesson).tasks.length){const a=x.active,t=byId.get(a.lesson).tasks[a.index],nw=t.answer.split(' ').length;r.active={lesson:a.lesson,index:a.index,draft:typeof a.draft==='string'?a.draft.slice(0,1200):'',choice:Number.isInteger(a.choice)&&a.choice>=0&&a.choice<(t.options?.length||0)?a.choice:null,words:Array.isArray(a.words)?[...new Set(a.words.filter(j=>Number.isInteger(j)&&j>=0&&j<nw))]:[],textMode:!!a.textMode,errors:Math.min(999,Math.max(0,Number(a.errors)||0)),earned:Math.max(0,Number(a.earned)||0),started:a.started||new Date().toISOString(),passed:!!a.passed,guided:!!byId.get(a.lesson).guided&&a.guided===true&&a.index>=byId.get(a.lesson).legacyCount,phase:a.phase==='theory'?'theory':'practice',theoryPage:Math.min((byId.get(a.lesson).guided?.cards.length||1)-1,Math.max(0,Math.floor(Number(a.theoryPage)||0))),materialOpen:!!a.materialOpen};if(!r.active.guided)r.active.phase='practice';}
 if(r.active){const a=x.active,w=validWarmup(a.warmup,r.completed);r.active.warmup=w;if(a.phase==='warmup')r.active.phase=w?'warmup':r.active.guided?'theory':'practice';}
 for(const [id,v] of Object.entries(x.journal||{}))if(byId.has(id)&&typeof v==='string')r.journal[id]=v.slice(0,3000);
 r.practiceDone=transfer.validDone(x.practiceDone);r.practiceActive=transfer.validActive(x.practiceActive);if(r.practiceActive&&!r.completed[r.practiceActive.lesson])r.practiceActive=null;
 r.plushAssignments=window.PLUSH_COLLECTION.assignments(x.plushAssignments,r.practiceDone);for(const [id,at] of Object.entries(x.achievementDates||{}))if(/^[a-z0-9-]+$/.test(id)&&typeof at==='string'&&Number.isFinite(Date.parse(at)))r.achievementDates[id]=at;
 r.drillHistory=window.LearningCore.validHistory(x.drillHistory);r.drill=window.LearningCore.validActive(x.drill,r.completed);r.drillLast=window.LearningCore.validRecap(x.drillLast,r.completed);
 const s=x.settings||{};r.settings={motion:s.motion!==false,sound:s.sound===true,speed:[.7,.85,1,1.15,1.3].includes(s.speed)?s.speed:.85,goal:[5,10,20].includes(s.goal)?s.goal:10,start:byId.has(s.start)?s.start:'v1-17'};return r;
}
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}catch(e){storageOK=false;}
function save(){for(const b of badges())if(b.earned&&!state.achievementDates[b.id])state.achievementDates[b.id]=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;toast('Не удалось сохранить прогресс. Сделай резервную копию в профиле.');}syncHeader();}
const totalXP=()=>state.seedXP+Object.values(state.awards).reduce((a,b)=>a+b,0);
state.plushAssignments=window.PLUSH_COLLECTION.assignments(state.plushAssignments,state.practiceDone);if(storageOK)save();
const profilePlush=window.PLUSH_COLLECTION.install({app,icon,esc,modal,openModal,state:()=>state});
function localDay(at){const d=new Date(at);return Number.isFinite(d.getTime())?[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'):'';}
function today(){return localDay(Date.now());}
function plural(n,one,few,many){const k=n%100;return k>=11&&k<=14?many:n%10===1?one:n%10>=2&&n%10<=4?few:many;}
function validCalendarDay(day){if(!/^\d{4}-\d{2}-\d{2}$/.test(day))return false;const d=new Date(day+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===day;}
function previousDay(day){return new Date(Date.parse(day+'T12:00:00Z')-86400000).toISOString().slice(0,10);}
function streak(){let day=today(),n=0;if(!state.activity[day])day=previousDay(day);while(state.activity[day]){n++;day=previousDay(day);}return n;}
function completedCount(){return Object.keys(state.completed).length;}
function moduleProgress(m){return m.lessons.filter(id=>state.completed[id]).length;}
function badges(){return [
 {id:'first',title:'Первый эпизод',desc:'Заверши любой урок',icon:'play',earned:completedCount()>=1},
 {id:'clean',title:'Чистый дубль',desc:'Пройди новый урок без ошибок',icon:'shield',earned:Object.values(state.completed).some(x=>x.errors===0)},
 {id:'module',title:'Финал сезона',desc:'Заверши все уроки одного модуля',icon:'award',earned:C.modules.some(m=>moduleProgress(m)===m.lessons.length)},
 {id:'streak',title:'Три вечера',desc:'Занимайся 3 дня подряд',icon:'moon',earned:streak()>=3},
 {id:'listener',title:'На слух',desc:'Выполни 10 заданий на слух',icon:'headphones',earned:C.lessons.flatMap(l=>l.tasks.map((t,i)=>['listen','clip'].includes(t.type)&&state.awards[uid(l,i)]>0)).filter(Boolean).length>=10},
 {id:'xp',title:'В потоке',desc:'Набери 1000 XP',icon:'flame',earned:totalXP()>=1000},
 {id:'reader',title:'Внимательный',desc:'Выполни 25 заданий на чтение',icon:'book',earned:C.lessons.flatMap(l=>l.tasks.map((t,i)=>['read','vocab'].includes(t.type)&&state.awards[uid(l,i)]>0)).filter(Boolean).length>=25},
 {id:'ten',title:'Десять историй',desc:'Заверши 10 разных эпизодов',icon:'star',earned:completedCount()>=10},
 ...window.PLUSH_COLLECTION.badges(state),
 {id:'all',title:'Последний кадр',desc:'Пройди все эпизоды',icon:'award',earned:completedCount()===C.lessons.length}
 ];}
function syncHeader(){document.getElementById('header-xp').textContent=totalXP()+' XP';document.body.classList.toggle('reduce-motion',!state.settings.motion);}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4000);}
function openModal(title,body){modal.innerHTML=`<div class="modal-header"><h2>${esc(title)}</h2><button class="icon-btn" id="close-modal" aria-label="Закрыть">${icon('close')}</button></div><div class="modal-body">${body}</div>`;document.getElementById('close-modal').onclick=()=>modal.close();modal.showModal();}
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
modal.addEventListener('close',()=>{modal.querySelectorAll('audio').forEach(a=>a.pause());});
function stopSpeech(){if('speechSynthesis'in window)window.speechSynthesis.cancel();speaking=false;document.querySelectorAll('audio').forEach(a=>a.pause());}
function speak(text){
 if(!('speechSynthesis'in window)){toast('Озвучка не поддерживается. Используй текстовый режим.');return false;}
 stopSpeech();const u=new SpeechSynthesisUtterance(text),voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='en-US')||voices.find(v=>v.lang.startsWith('en'))||null;u.lang='en-US';u.rate=state.settings.speed;u.pitch=1;u.onstart=()=>{speaking=true;const e=document.getElementById('speech-status');if(e)e.textContent='Воспроизведение…';};u.onend=()=>{speaking=false;const e=document.getElementById('speech-status');if(e)e.textContent='Можно прослушать ещё раз';};u.onerror=()=>{speaking=false;toast('Голос недоступен на устройстве. Переключись в текстовый режим.');};speechSynthesis.speak(u);return true;
}
function feedbackTone(good){if(!state.settings.sound)return;try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;const ctx=new AudioCtx();ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.setValueAtTime(good?520:240,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(good?780:170,ctx.currentTime+.12);g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);o.start();o.stop(ctx.currentTime+.2);o.onended=()=>ctx.close();}catch(e){}}
function norm(s){return String(s).normalize('NFKC').toLowerCase().replace(/[’‘`]/g,"'").replace(/\b(can't|cannot)\b/g,'can not').replace(/\bwon't\b/g,'will not').replace(/\bshan't\b/g,'shall not').replace(/\b(let's)\b/g,'let us').replace(/\b(\w+)n't\b/g,'$1 not').replace(/\bi'm\b/g,'i am').replace(/\b(you|we|they)'re\b/g,'$1 are').replace(/\b(i|you|we|they)'ve\b/g,'$1 have').replace(/\b(he|she|it|that|there|what|who)'s (?=(?:already |just |never )?(?:been|seen|done|gone|finished|left|worked|played|forgotten|arrived)\b)/g,'$1 has ').replace(/\b(he|she|it|that|there|what|who)'s\b/g,'$1 is').replace(/\b(\w+)'ll\b/g,'$1 will').replace(/[^a-z0-9ɪ'\s]/g,' ').replace(/\s+/g,' ').trim();}
function writtenForms(value){const n=norm(value),forms=new Set([n]);for(const d of ['had','would'])forms.add(n.replace(/\b(i|you|he|she|it|we|they)'d\b/g,'$1 '+d));for(const f of [...forms])forms.add(f.replace(/\b(he|she|it|that|there)'s (?=(?:already |just |never )?(?:been|seen|done|gone|finished|left|worked|played|forgotten|arrived)\b)/g,'$1 has '));return forms;}
function matches(value,t){const values=writtenForms(value);return [t.answer,...(t.accept||[])].some(a=>[...writtenForms(a)].some(f=>values.has(f)));}
function shuffle(a,seed=17){const b=[...a];let n=seed;for(let i=b.length-1;i>0;i--){n=(n*1664525+1013904223)>>>0;const j=n%(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;}
function nextLesson(){if(state.active)return byId.get(state.active.lesson);const start=C.lessons.findIndex(l=>l.id===state.settings.start);return C.lessons.slice(start).find(l=>!state.completed[l.id])||C.lessons.find(l=>!state.completed[l.id])||C.lessons[start];}
const image=l=>`assets/${l.image}.webp`;
function card(l){const done=state.completed[l.id],active=state.active?.lesson===l.id,gate=lessonGate(l.id);return `<button class="episode-card ${gate?'rhythm-locked-card':''}" data-lesson="${l.id}" aria-label="${esc(l.ru)}, ${done?'пройден':active?'продолжить':gate?'закрыто':'начать'}"><div class="episode-image"><img src="${image(l)}" alt="${esc(C.images[l.image])}" loading="lazy"><span class="episode-badge">${done?'✓ Пройден':active?'Продолжить':gate?'Закрыто':l.band}</span></div><div class="episode-info"><div class="eyebrow">Эпизод ${l.number} · Курс ${l.level}</div><h3>${esc(l.ru)}</h3><p>${l.tasks.length-(l.legacyCount||0)} заданий · ${l.tasks.length-l.legacyCount>10?'10–15':l.level===1?'6–10':'8–12'} мин</p></div></button>`;}
function bindCards(){app.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>location.hash='lesson/'+b.dataset.lesson);}
function home(){
 const done=completedToday(),pending=nextLesson(),l=byId.get(state.active?.lesson)||(done?byId.get(done):pending),allDone=completedCount()===C.lessons.length,m=C.modules.find(m=>m.lessons.includes(l.id)),hour=new Date().getHours(),greeting=hour<5?'Твой вечер':hour<12?'Доброе утро':hour<18?'Добрый день':'Твой вечер',finished=(done&&!state.active)||allDone;
 const next=allDone?null:pending.id!==l.id?pending:C.lessons.slice(C.lessons.indexOf(l)+1).find(x=>!state.completed[x.id])||C.lessons.find(x=>!state.completed[x.id]&&x.id!==l.id);
 return `<div class="view redesigned-home reference-home"><div class="home-intro"><h1>${finished?'Хорошая работа':greeting}, ${esc(state.name)}</h1></div>${!storageOK?'<p class="storage-warning">Сохранение недоступно. Экспортируй прогресс в настройках.</p>':''}<section class="hero ${finished?'today-finished':''}"><img src="${image(l)}" alt="${esc(C.images[l.image])}" fetchpriority="high"><div class="hero-body"><span class="hero-tag">${finished?'Эпизод '+l.number+' завершён':'Эпизод '+l.number+' · '+l.band}</span><h1>${esc(l.ru)}</h1>${finished?'':`<p>${esc(l.guided?.cards[0]?.title||l.hook)}</p><button class="primary" data-lesson="${l.id}">${state.active?'Продолжить эпизод':'Начать эпизод'} ${icon('chevron')}</button>`}</div></section>${finished?`<section class="today-actions"><div class="section-head"><h2>${allDone?'Продолжим практику':'Закрепим сегодняшнюю тему'}</h2></div><div class="today-timeline"><a href="#lesson/${l.id}" class="today-row completed-row"><span class="today-icon">${icon('check')}</span><div><h3>Урок пройден</h3><p>${esc(l.guided?.cards[0]?.title||l.ru)}</p></div></a><a href="#transfer/${l.id}" class="today-row"><span class="today-icon">${icon(state.practiceDone[l.id]?'check':'practice')}</span><div><h3>Практика</h3><p>${state.practiceDone[l.id]?'Пройдено · Можно повторить':'4 задания · Новая игрушка'}</p></div>${icon('chevron')}</a><a href="#speaking/${l.id}" class="today-row"><span class="today-icon">${icon('conversation')}</span><div><h3>Разговор</h3><p>Новая ситуация по этой теме</p></div>${icon('chevron')}</a></div></section>`:''}<section class="current-season"><div class="section-head"><h2>Текущий модуль</h2><a class="text-link" href="#library">Все модули ${icon('arrow')}</a></div><a class="season-card" href="#module/${m.id}" aria-label="${esc(m.title)}, ${moduleProgress(m)} из ${m.lessons.length} эпизодов"><img src="${m.number===1?'assets/first-meetings.webp':image(byId.get(m.lessons[0]))}" alt="" loading="lazy"><div class="season-copy"><h3>${esc(m.title)}</h3><p>${moduleProgress(m)} из ${m.lessons.length} эпизодов</p></div><div class="season-stops">${m.lessons.map((id,i)=>`<span class="season-stop ${state.completed[id]?'done':id===pending.id?'current':lessonGate(id)?'locked':''}" aria-label="Эпизод ${i+1}: ${state.completed[id]?'пройден':id===pending.id?'следующий':lessonGate(id)?'закрыт':'доступен'}"><span class="stop-dot">${state.completed[id]?icon('check'):id===pending.id?i+1:lessonGate(id)?icon('lock'):i+1}</span><small>${i+1}</small></span>`).join('')}</div></a></section>${next?`<a class="next-teaser" href="#lesson/${next.id}"><img src="${image(next)}" alt="" loading="lazy"><span class="next-copy"><span>Следующий эпизод</span><strong>${esc(next.ru)}</strong><small>${state.active?'После текущего урока':'Можно начать сейчас'}</small></span>${icon('chevron')}</a>`:allDone?'<p class="source-note">Все 82 эпизода пройдены. Правила, практика и коллекция остаются доступны.</p>':''}</div>`;
}
function moduleRow(m){const n=moduleProgress(m);return `<a href="#module/${m.id}" class="module-row"><span class="module-number">${m.number.toString().padStart(2,'0')}</span><div><h3>${esc(m.title)}</h3><p>${m.band} · ${n} из ${m.lessons.length} эпизодов</p><div class="progress-track"><span style="width:${n/m.lessons.length*100}%"></span></div></div>${icon('chevron')}</a>`;}
function library(filter='all'){let lessons=C.lessons;if(filter==='1'||filter==='2')lessons=lessons.filter(l=>l.level===+filter);if(filter==='done')lessons=lessons.filter(l=>state.completed[l.id]);return `<div class="view library-head"><div class="eyebrow">Коллекция историй</div><h1 style="margin-top:10px">Выбери свой эпизод</h1><p>82 эпизода в твоём темпе. Новые уроки и повторение доступны без дневного лимита.</p><div class="filters">${[['all','Все'],['1','Основы'],['2','Продолжение'],['done','Пройденные']].map(([id,label])=>`<button class="chip ${filter===id?'active':''}" data-filter="${id}">${label}</button>`).join('')}</div>${lessons.length?`<div class="library-grid">${lessons.map(card).join('')}</div>`:'<div class="empty"><h2>Здесь появятся твои эпизоды</h2><p>Заверши первый урок — и он останется в коллекции.</p></div>'}<div class="section-head"><h2>Все сезоны</h2></div><div class="module-list">${C.modules.map(moduleRow).join('')}</div></div>`;}
function moduleView(id){const m=C.modules.find(m=>m.id===id);if(!m)return home();return `<div class="view"><div class="breadcrumbs"><a href="#library">${icon('back')}</a> Все эпизоды</div><div class="eyebrow">Сезон ${m.number} · ${m.band}</div><h1 style="margin-top:12px">${esc(m.title)}</h1><p class="muted" style="margin:15px 0 25px">${moduleProgress(m)} из ${m.lessons.length} эпизодов пройдено</p><div class="library-grid">${m.lessons.map(id=>card(byId.get(id))).join('')}</div></div>`;}
function renderLessonLock(id){const l=byId.get(state.active?.lesson)||byId.get(id);app.innerHTML=`<div class="view rhythm-lock"><div class="rhythm-lock-art"><img src="${image(l)}" alt="${esc(C.images[l.image])}"></div><div class="eyebrow">Сохраним начатое</div><h1>Продолжим начатый урок</h1><p>Незаконченный эпизод «${esc(l.ru)}» сохранён. Сначала заверши его, чтобы сохранить текущую попытку.</p><div class="rhythm-lock-actions"><a class="primary" href="#lesson/${l.id}">Продолжить урок ${icon('arrow')}</a><a class="text-link" href="#library">Все эпизоды ${icon('back')}</a></div></div>`;}
function renderWarmup(){const w=session.warmup,l=byId.get(w.source),next=byId.get(session.lesson),t=window.WARMUP_BANK[w.source][w.index],tokens=t.type==='order'?shuffle(t.answer.split(' '),w.index*37+l.number*101):[];const field=t.type==='order'?`<div class="sentence-tray" aria-label="Собранная фраза">${w.words.map(j=>`<button class="word" data-warm-remove="${j}" lang="en" ${w.passed?'disabled':''}>${esc(tokens[j])}</button>`).join('')}</div><div class="word-bank">${tokens.map((word,j)=>`<button class="word ${w.words.includes(j)?'used':''}" data-warm-word="${j}" lang="en" ${w.passed||w.words.includes(j)?'disabled':''}>${esc(word)}</button>`).join('')}</div>`:`<label class="answer-label" for="warm-answer">${t.type==='gap'?'Пропущенное слово':'Исправленная реплика'}</label><textarea id="warm-answer" class="response" lang="en" spellcheck="false" maxlength="1200" rows="2" ${w.passed?'disabled':''}>${esc(w.draft)}</textarea>`;app.innerHTML=`<div class="view warmup-view"><div class="lesson-top"><a class="icon-btn" href="#home" aria-label="Выйти, сохранив повторение">${icon('back')}</a><div class="progress-track" role="progressbar" aria-label="Повторение предыдущей темы" aria-valuemin="0" aria-valuemax="3" aria-valuenow="${w.index+(w.passed?1:0)}"><span style="width:${(w.index+(w.passed?1:0))/3*100}%"></span></div><span class="lesson-count">Повторение ${w.index+1}/3</span></div><div class="lesson-layout"><div class="scene-image"><img src="${image(l)}" alt="${esc(C.images[l.image])}"><div class="scene-caption"><div class="eyebrow">Вспомним прошлую тему</div><h2>${esc(l.guided.cards[0].title)}</h2><p>${esc(l.ru)}</p></div></div><section class="exercise-panel"><div class="teacher"><img src="assets/margo.webp" alt="Аватар ведущей Марго"><div>Марго<small>Твоя ведущая</small></div></div><div class="eyebrow">Перед новой темой · Без XP</div><h1>${esc(t.heading)}</h1><p class="exercise-prompt">${esc(t.prompt)}</p>${t.display?`<div class="source-excerpt ${t.type==='gap'?'cloze':''}" lang="en">${esc(t.display)}</div>`:''}<div id="warm-field">${field}</div><div id="warm-feedback" role="status" aria-live="polite">${w.passed?`<div class="feedback"><div class="feedback-title">Вспомнили</div><p>${esc(t.explanation)}</p></div>`:''}</div><div class="exercise-actions"><button class="primary" id="warm-check">${w.passed?w.index===2?'К новой теории':'Следующий вопрос':'Проверить'} ${icon('arrow')}</button></div><details class="warm-rule"><summary>Вспомнить правило</summary><p>${esc(t.explanation)}</p><p>${esc(t.hint)}</p></details><p class="warm-next">Дальше — ${esc(next.guided.cards[0].title)}</p></section></div></div>`;
const check=document.getElementById('warm-check'),input=document.getElementById('warm-answer');const enabled=()=>check.disabled=!w.passed&&(t.type==='order'?w.words.length!==tokens.length:!w.draft.trim());if(input)input.oninput=()=>{w.draft=input.value;persistSession();enabled();};app.querySelectorAll('[data-warm-word]').forEach(b=>b.onclick=()=>{w.words.push(+b.dataset.warmWord);persistSession();renderWarmup();app.querySelector('[data-warm-word]:not(:disabled)')?.focus({preventScroll:true});});app.querySelectorAll('[data-warm-remove]').forEach(b=>b.onclick=()=>{w.words=w.words.filter(j=>j!==+b.dataset.warmRemove);persistSession();renderWarmup();});check.onclick=()=>{if(w.passed){check.disabled=true;if(w.index===2){session.phase=session.guided?'theory':'practice';Object.assign(session,{draft:'',choice:null,words:[],passed:false});}else{w.index++;Object.assign(w,{draft:'',words:[],passed:false});}persistSession();transition(()=>renderLesson(),true);return;}const value=t.type==='order'?w.words.map(j=>tokens[j]).join(' '):w.draft;if(matches(value,t)){w.passed=true;w.draft=value;state.activity[today()]=(state.activity[today()]||0)+1;persistSession();renderWarmup();feedbackTone(true);}else{w.errors++;persistSession();document.getElementById('warm-feedback').innerHTML=`<div class="feedback bad"><div class="feedback-title">Уточним конструкцию</div><p>${esc(t.explanation)}</p><details><summary>Разобрать ответ</summary><p lang="en">${esc(t.answer)}</p></details></div>`;feedbackTone(false);}};enabled();}

function completedToday(){return Object.entries(state.completed).filter(([,v])=>(v.day||localDay(v.at))===today()).sort((a,b)=>b[1].at.localeCompare(a[1].at))[0]?.[0]||null;}
function lessonGate(id){if(state.completed[id]||state.active?.lesson===id)return '';if(state.active&&!state.completed[state.active.lesson])return 'unfinished';return '';}
function latestCompleted(exclude){return Object.entries(state.completed).filter(([id])=>id!==exclude).sort((a,b)=>b[1].at.localeCompare(a[1].at))[0]?.[0]||null;}
function validWarmup(raw,completed){if(!raw||!completed[raw.source]||!window.WARMUP_BANK[raw.source]||!Number.isInteger(raw.index)||raw.index<0||raw.index>=3)return null;const t=window.WARMUP_BANK[raw.source][raw.index],nw=t.answer.split(' ').length;const draft=typeof raw.draft==='string'?raw.draft.slice(0,1200):'';return {source:raw.source,index:raw.index,draft,words:Array.isArray(raw.words)?[...new Set(raw.words.filter(j=>Number.isInteger(j)&&j>=0&&j<nw))]:[],passed:raw.passed===true&&matches(draft,t),errors:Math.min(999,Math.max(0,Number.isFinite(Number(raw.errors))?Number(raw.errors):0))};}
function startSession(id,review=false,reviewTasks=null){const l=byId.get(id);if(!l){session=null;return false;}if(review){session={lesson:id,index:0,draft:'',choice:null,words:[],errors:0,earned:0,passed:false,review:true,reviewTasks};return true;}
 if(lessonGate(id)){session=null;return false;}if(state.active?.lesson===id&&!state.completed[id]){session={...state.active};return true;}
 const replay=!!state.completed[id],source=replay?null:latestCompleted(id),warmup=source&&window.WARMUP_BANK[source]?{source,index:0,draft:'',words:[],passed:false,errors:0}:null;
 session={lesson:id,index:l.guided?l.legacyCount:0,guided:!!l.guided,phase:warmup?'warmup':l.guided?'theory':'practice',warmup,theoryPage:0,materialOpen:false,draft:'',choice:null,words:[],errors:0,earned:0,started:new Date().toISOString(),passed:false,replay};if(!replay){state.active={...session};save();}return true;}
function currentTask(){if(session.reviewTasks)return session.reviewTasks[session.index];return {l:byId.get(session.lesson),i:session.index,t:byId.get(session.lesson).tasks[session.index]};}
function persistSession(){if(session&&!session.review&&!session.replay){state.active={...session};save();}}
function taskEnd(){const l=byId.get(session.lesson);return session.reviewTasks?.length||(session.guided?l.tasks.length:(l.legacyCount||l.tasks.length));}
function taskStart(){return session.guided&&!session.review?byId.get(session.lesson).legacyCount:0;}
function theoryCard(c){return `<div class="theory-content"><p class="theory-lead">${esc(c.lead)}</p><div class="theory-rule">${esc(c.rule)}</div><div class="theory-examples">${c.examples.map(([a,b])=>c.exampleStyle==='translation'?`<div><strong lang="en">${esc(a)}</strong><span>${esc(b)}</span></div>`:`<div><span lang="en">${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('')}</div><p class="theory-note">${esc(c.note)}</p>${c.takeaway?`<p class="theory-takeaway">${icon('check')}<span>${esc(c.takeaway)}</span></p>`:''}</div>`;}
function sourceBody(l){return `${l.guided?`<div class="material-theory">${l.guided.cards.map(c=>`<details><summary>${esc(c.title)}</summary>${theoryCard(c)}</details>`).join('')}</div>`:''}${l.audio?`<details class="source-recording"><summary>Полная запись · онлайн</summary><audio controls preload="none" src="${esc(l.audio)}" aria-label="Полный диалог"></audio></details>`:''}<details><summary>Полный диалог</summary><div class="transcript" lang="en">${esc(l.dialogue.join('\n\n'))}</div></details><details><summary>Источники</summary><p><a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">Let’s Learn English · Учебные материалы ↗</a>${l.guided?.source&&l.guided.source!==l.url?`<br><a href="${esc(l.guided.source)}" target="_blank" rel="noopener noreferrer">${esc(l.guided.sourceLabel||'Грамматический справочник')} ↗</a>`:''}</p></details>`;}
function materialHTML(l){return `<details class="lesson-material" id="lesson-material" ${session.materialOpen?'open':''}><summary>${icon('book')}<span>Материал урока</span>${icon('chevron')}</summary><div class="material-body">${sourceBody(l)}</div></details>`;}
function bindMaterial(){const d=document.getElementById('lesson-material');if(!d)return;d.querySelector(':scope>summary').addEventListener('click',()=>{session.materialOpen=!d.open;persistSession();});d.addEventListener('toggle',()=>{if(!d.isConnected||!session)return;session.materialOpen=d.open;persistSession();if(!d.open)d.querySelectorAll('audio').forEach(a=>a.pause());});d.querySelectorAll('audio').forEach(a=>{a.playbackRate=state.settings.speed;});d.querySelectorAll('.source-recording').forEach(el=>el.addEventListener('toggle',()=>{if(!el.open)el.querySelector('audio')?.pause();}));}
function theoryHTML(){const l=byId.get(session.lesson),n=session.theoryPage,c=l.guided.cards[n];return `<div class="view"><div class="lesson-top" data-session="${l.id}-theory"><button class="icon-btn" id="exit-lesson" aria-label="Выйти из урока">${icon('back')}</button><div class="theory-dots" aria-label="Теория: страница ${n+1} из ${l.guided.cards.length}">${l.guided.cards.map((_,i)=>`<span class="${i<=n?'done':''}"></span>`).join('')}</div><span class="lesson-count">Теория ${n+1}/${l.guided.cards.length} · ${l.band}</span></div><div class="lesson-layout"><div class="scene-image"><img src="${image(l)}" alt="${esc(C.images[l.image])}"><div class="scene-caption"><div class="eyebrow">Эпизод ${l.number}</div><h2>${esc(l.ru)}</h2><p>${esc(l.title)}</p></div></div><section class="exercise-panel theory-panel"><div class="teacher"><img src="assets/margo.webp" alt="Аватар ведущей Марго"><div>Марго<small>Твоя ведущая</small></div></div><div class="eyebrow">Перед практикой</div><h1>${esc(c.title)}</h1>${theoryCard(c)}<div class="theory-actions">${n?`<button class="secondary" id="theory-back" aria-label="Предыдущая страница теории">${icon('back')}</button>`:''}<button class="primary" id="theory-next">${n===l.guided.cards.length-1?'Перейти к практике':'Дальше'} ${icon('arrow')}</button></div>${materialHTML(l)}</section></div></div>`;}
function bindTheory(){document.getElementById('exit-lesson').onclick=()=>location.hash='home';document.getElementById('theory-next').onclick=e=>{e.currentTarget.disabled=true;if(session.theoryPage<byId.get(session.lesson).guided.cards.length-1)session.theoryPage++;else session.phase='practice';persistSession();transition(()=>renderLesson(),true);};const back=document.getElementById('theory-back');if(back)back.onclick=e=>{e.currentTarget.disabled=true;session.theoryPage--;persistSession();transition(()=>renderLesson(),true);};bindMaterial();}
function diagnostic(t){let value=session.draft;if(t.options)value=t.options[session.choice]||'';const v=norm(value);return (t.diagnostics||[]).find(d=>new RegExp(d.pattern).test(v))?.message||t.hint;}
function lessonHTML(){if(session.guided&&session.phase==='theory'&&!session.review)return theoryHTML();const {l,t,i}=currentTask(),count=taskEnd()-taskStart();const n=session.index-taskStart();let field='';const choice=session.choice;const tokens=t.type==='order'?shuffle(t.answer.split(' '),i*37+l.number*101):[];
 if(t.options)field=`<div class="options" role="group" aria-label="Варианты ответа">${t.options.map((o,j)=>`<button class="option ${choice===j?'selected':''}" data-choice="${j}" aria-pressed="${choice===j}" ${session.passed?'disabled':''}><span class="option-index">${j+1}</span><span lang="en">${esc(o)}</span></button>`).join('')}</div>`;
 else if(t.type==='order')field=`<div class="sentence-tray" aria-label="Собранная фраза">${session.words.filter(j=>j>=0&&j<tokens.length).map(j=>`<button class="word" data-remove="${j}" lang="en" ${session.passed?'disabled':''}>${esc(tokens[j])}</button>`).join('')}</div><div class="word-bank" aria-label="Слова для фразы">${tokens.map((w,j)=>`<button class="word ${session.words.includes(j)?'used':''}" data-word="${j}" lang="en" ${session.words.includes(j)||session.passed?'disabled':''}>${esc(w)}</button>`).join('')}</div>`;
 else field=`<label class="answer-label" for="answer">${t.type==='gap'?'Пропущенное слово':'Твоя реплика'}</label><textarea class="response" id="answer" lang="en" autocomplete="off" autocapitalize="sentences" spellcheck="false" maxlength="1200" placeholder="${t.type==='gap'?'…':'Your answer…'}" ${session.passed?'disabled':''}>${esc(session.draft)}</textarea>`;
 return `<div class="view"><div class="lesson-top" data-session="${session.review?'review':session.lesson}"><button class="icon-btn" id="exit-lesson" aria-label="Выйти из урока">${icon('back')}</button><div class="progress-track" role="progressbar" aria-label="Прогресс эпизода" aria-valuenow="${n}" aria-valuemin="0" aria-valuemax="${count}"><span style="width:${n/count*100}%"></span></div><span class="lesson-count">${session.review?'Практика':'Задание'} ${n+1}/${count} · ${l.band}</span></div><div class="lesson-layout"><div class="scene-image"><img src="${image(l)}" alt="${esc(C.images[l.image])}"><div class="scene-caption"><div class="eyebrow">${session.review?'Ещё один дубль':'Эпизод '+l.number}</div><h2>${esc(l.ru)}</h2><p>${esc(l.title)}</p></div></div><section class="exercise-panel"><div class="teacher"><img src="assets/margo.webp" alt="Аватар ведущей Марго"><div>Марго<small>Твоя ведущая</small></div></div><div class="eyebrow">${esc(t.label)}${t.type==='reflection'?' · Без оценки':' · '+t.xp+' XP'}</div><h1>${esc(t.heading)}</h1><p class="exercise-prompt">${esc(t.prompt)}</p>${t.display?`<div class="source-excerpt cloze" lang="en">${esc(t.display)}</div>`:''}${t.context?`<div class="source-excerpt" lang="en">${esc(t.context)}</div>`:''}${t.type==='clip'?`<div class="clip-card"><div class="clip-heading"><span class="eyebrow">Запись сцены</span>${speedControl()}</div><audio id="clip-audio" controls preload="metadata" src="${esc(t.audioFile)}" aria-label="Сцена оригинального урока"></audio></div>`:''}${t.type==='listen'?`<div class="audio-card"><button class="icon-btn" id="play-audio" aria-label="Прослушать реплику">${icon('volume')}</button><div><strong>Послушай реплику</strong><p>Голос устройства · английский</p><div class="speech-status" id="speech-status" role="status">${'speechSynthesis'in window?'Нажми на значок звука':'Озвучка недоступна'}</div></div>${speedControl()}</div><button class="text-link" id="text-mode">Текстовый режим</button>`:''}<div id="answer-field">${field}</div><div id="feedback" role="status" aria-live="polite"></div><div class="exercise-actions"><button class="primary" id="check-answer">${session.passed?'Следующее задание':t.type==='reflection'?'Сохранить историю':'Проверить'} ${icon('arrow')}</button></div>${materialHTML(l)}<div class="help-row"><button id="task-help">${icon('info')} ${t.type==='order'?'Как собрать фразу':'О задании'}</button></div></section></div></div>`;
}
function bindLesson(){const {l,t,i}=currentTask();let tokens=t.type==='order'?shuffle(t.answer.split(' '),i*37+l.number*101):[];const check=document.getElementById('check-answer');
 function enabled(){check.disabled=!session.passed&&!(t.options?session.choice!==null:t.type==='order'?session.words.length===tokens.length:session.draft.trim().length>0);}
 app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{session.choice=+b.dataset.choice;app.querySelectorAll('[data-choice]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});persistSession();enabled();});
 app.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{session.words.push(+b.dataset.word);persistSession();renderLesson(false);(app.querySelector('[data-word]:not(:disabled)')||app.querySelector('[data-remove]'))?.focus({preventScroll:true});});
 app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const removed=b.dataset.remove;session.words=session.words.filter(j=>j!==+removed);persistSession();renderLesson(false);app.querySelector('[data-word="'+removed+'"]')?.focus({preventScroll:true});});
 const input=document.getElementById('answer');if(input){input.oninput=()=>{session.draft=input.value.slice(0,1200);persistSession();enabled();};input.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!check.disabled)check.click();};}
 check.onclick=()=>{if(session.passed){check.disabled=true;advance();return;}const value=t.options?t.options[session.choice]:t.type==='order'?session.words.map(j=>tokens[j]).join(' '):session.draft;if(t.type==='reflection'||matches(value,t)){if(t.type==='reflection')state.journal[l.id]=value;session.passed=true;const key=uid(l,i),awardKey=t.awardKey||key,was=state.awards[awardKey];let xp=0;if(!session.review&&!session.replay&&!was&&!session.textMode&&t.xp>0){xp=t.xp;state.awards[awardKey]=xp;session.earned+=xp;}if(state.mistakes[key])delete state.mistakes[key];if(t.awardKey&&state.mistakes[t.awardKey])delete state.mistakes[t.awardKey];state.activity[today()]=(state.activity[today()]||0)+1;persistSession();save();showFeedback(true,t,xp,!!was||session.review);check.disabled=false;check.innerHTML=`${session.index+1===taskEnd()?'Завершить эпизод':'Следующее задание'} ${icon('arrow')}`;app.querySelectorAll('#answer-field button,#answer').forEach(b=>b.disabled=true);feedbackTone(true);}else{session.errors++;const key=uid(l,i);state.mistakes[key]={count:(state.mistakes[key]?.count||0)+1,due:Date.now()};persistSession();save();showFeedback(false,t,0,false);feedbackTone(false);}};
 document.getElementById('exit-lesson').onclick=()=>{stopSpeech();location.hash=session.review?'practice':'home';};bindMaterial();document.getElementById('task-help').onclick=()=>openModal(t.heading,`<p>${esc(t.help||'Тренируем конструкцию в контексте урока. Регистр и знаки препинания не влияют на оценку. Сокращения вроде I’m и I am принимаются одинаково.')}</p>`);
 const speed=document.getElementById('exercise-speed'),clip=document.getElementById('clip-audio');
 if(clip){clip.playbackRate=state.settings.speed;clip.addEventListener('loadedmetadata',()=>{clip.playbackRate=state.settings.speed;});}
 if(speed)speed.onchange=()=>{state.settings.speed=+speed.value;save();app.querySelectorAll('audio').forEach(a=>a.playbackRate=state.settings.speed);if(speaking)speak(t.audioText||t.answer);};
 const play=document.getElementById('play-audio');if(play)play.onclick=()=>speak(t.audioText||t.answer);
 const tm=document.getElementById('text-mode');if(tm)tm.onclick=()=>{stopSpeech();const box=document.querySelector('.audio-card');box.innerHTML=`<div><strong>Прочитай и восстанови реплику</strong><p lang="en" style="font-size:18px;margin-top:8px;color:var(--ink)">${esc(t.answer)}</p><p>Эта попытка — практика чтения, без XP за аудирование.</p></div>`;session.textMode=true;persistSession();tm.remove();};
 if(session.textMode&&tm)tm.click();
 if(session.passed){showFeedback(true,t,0,true);check.innerHTML=`${session.index+1===taskEnd()?'Завершить эпизод':'Следующее задание'} ${icon('arrow')}`;}enabled();
}
function showFeedback(good,t,xp,replay){const el=document.getElementById('feedback');el.innerHTML=good&&t.type==='reflection'?`<div class="feedback"><div class="feedback-title">История сохранена</div><p>${esc(t.explanation)}</p><details><summary>Сравнить с примером</summary><p lang="en">${esc(t.answer)}</p></details></div>`:good?`<div class="feedback"><div class="feedback-title"><span>Отличный дубль</span><span>${replay?'✓': '+'+xp+' XP'}</span></div><p>${esc(t.explanation)}</p></div>`:`<div class="feedback bad"><div class="feedback-title"><span>Попробуем ещё раз</span></div><p>${esc(diagnostic(t)||'Вернись к фрагменту сцены: важно восстановить исходную реплику. Проверь порядок слов и форму глагола.')}</p><button class="secondary" id="reveal-answer">Разобрать ответ</button></div>`;
 const reveal=document.getElementById('reveal-answer');if(reveal)reveal.onclick=()=>{el.querySelector('.feedback').innerHTML=`<div class="feedback-title">Разбор</div><p class="correct-answer" lang="en">${esc(t.answer)}</p><p>${esc(t.explanation)}</p><p class="muted">Восстанови реплику ещё раз, чтобы закрепить.</p>`;};}
function renderLesson(animate=true){if(session.phase==='warmup'&&session.warmup){renderWarmup();syncHeader();return;}const old=app.querySelector('.lesson-top'),previous=old?.dataset.session===(session.review?'review':session.lesson)?old.querySelector('.progress-track>span').style.width:null;app.innerHTML=lessonHTML();const bar=app.querySelector('.lesson-top .progress-track>span');if(previous!==null&&bar){const target=bar.style.width;bar.style.width=previous;requestAnimationFrame(()=>requestAnimationFrame(()=>bar.style.width=target));}if(!animate)app.querySelector('.view').style.animation='none';if(session.guided&&session.phase==='theory'&&!session.review)bindTheory();else bindLesson();syncHeader();}
function advance(){stopSpeech();const count=taskEnd();if(session.index+1>=count){finish();return;}session.index++;Object.assign(session,{draft:'',choice:null,words:[],passed:false,textMode:false});persistSession();transition(()=>renderLesson(),true);}
function finish(){const l=byId.get(session.lesson),oldBadges=badges().filter(b=>b.earned).map(b=>b.id);if(!session.review&&!session.replay){if(!state.completed[l.id])state.completed[l.id]={at:new Date().toISOString(),day:today(),errors:session.errors,earned:session.earned};if(session.guided)state.completed[l.id].guidedDone=true;state.active=null;save();}const unlocked=badges().filter(b=>b.earned&&!oldBadges.includes(b.id));const data={l,errors:session.errors,earned:session.earned,review:session.review||session.replay,unlocked};session=null;location.hash='complete/'+l.id;sessionStorage.setItem('afterhours.recap',JSON.stringify({id:l.id,errors:data.errors,earned:data.earned,review:data.review,unlocked:unlocked.map(b=>b.id)}));renderRecap(data);}
function renderRecap(data){const {l,errors,earned,review,unlocked=[]}=data,next=!review&&completedCount()<C.lessons.length?nextLesson():null;app.innerHTML=`<div class="view lesson-recap"><img class="recap-art" src="${image(l)}" alt="${esc(C.images[l.image])}"><div class="recap-orbit">✓</div><div class="eyebrow">${review?'Повторение завершено':'Эпизод завершён'}</div><h1>Хорошая история.<br>Хорошая работа.</h1><p class="muted">${esc(l.ru)}</p><div class="recap-stats"><div class="stat"><strong>+${earned}</strong><span>XP за эпизод</span></div><div class="stat"><strong>${errors}</strong><span>ошибки в попытке</span></div><div class="stat"><strong>${totalXP()}</strong><span>общий XP</span></div></div>${unlocked.map(b=>`<div class="unlock">✦ Новое достижение: ${esc(b.title)}</div>`).join('')}<div class="recap-buttons"><a class="primary" href="#${review?'practice':'transfer/'+l.id}">${review?'К практике':'Закрепить тему'} ${icon('arrow')}</a><a class="secondary" href="#profile">Мой прогресс</a>${next?`<a class="secondary" href="#lesson/${next.id}">Следующий эпизод ${icon('arrow')}</a>`:''}</div><p class="source-note">${review?'':'Эпизод завершён. Можно закрепить тему, поговорить на английском или сразу начать следующий урок.'}</p></div>`;}
function sourcesModal(){openModal('Учебные источники',`<p>Последовательность уроков, темы и диалоги — из Let’s Learn English, курса сертифицированных американских преподавателей. Объяснения на русском и упражнения адаптированы для приложения.</p><div class="source-item"><a href="https://learningenglish.voanews.com/p/5644.html" target="_blank" rel="noopener noreferrer">Let’s Learn English · Основы ↗</a></div><div class="source-item"><a href="https://learningenglish.voanews.com/p/6765.html" target="_blank" rel="noopener noreferrer">Let’s Learn English · Продолжение ↗</a></div><div class="source-item"><a href="https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference" target="_blank" rel="noopener noreferrer">British Council · Грамматический справочник ↗</a></div><p>Тексты исходного курса, созданные Voice of America, опубликованы в public domain. <a href="https://learningenglish.voanews.com/p/6021.html" target="_blank" rel="noopener noreferrer">Условия использования ↗</a></p><p>Метки A1–A2 и A2–B1 — ориентир сложности. Они не заменяют официальную оценку уровня.</p><p>Учебные ответы проверяются по ожидаемым формам и допустимым вариантам. Свои истории сохраняются в дневнике без автоматической оценки грамматики.</p><p>Марго — вымышленная ведущая с предоставленным пользователем аватаром.</p>`);}
function practice(){return learning.practiceHome();}
const SPEEDS=[.7,.85,1,1.15,1.3];
const speedLabel=v=>String(v).replace('.',',')+'×';
function speedControl(){return `<label class="audio-speed"><span class="sr-only">Скорость воспроизведения</span><select id="exercise-speed" aria-label="Скорость воспроизведения">${SPEEDS.map(v=>`<option value="${v}" ${state.settings.speed===v?'selected':''}>${speedLabel(v)}</option>`).join('')}</select></label>`;}
function bestStreak(){let best=0,n=0,last='';for(const day of Object.keys(state.activity).filter(d=>state.activity[d]>0).sort()){n=previousDay(day)===last?n+1:1;best=Math.max(best,n);last=day;}return best;}
function achievementArt(b){const earned=b?.earned===true,id='award-'+(b?.id||'empty'),symbol=paths[earned?b.icon:'lock']||paths.trophy;return `<span class="award-art ${earned?'is-earned':'is-locked'}" data-award="${esc(b?.id||'empty')}"><svg viewBox="0 0 100 112" aria-hidden="true"><defs><linearGradient id="${id}-edge" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${earned?'#ffe4a4':'#a590b4'}"/><stop offset=".48" stop-color="${earned?'#dba04b':'#645170'}"/><stop offset="1" stop-color="${earned?'#f5c46e':'#8f749e'}"/></linearGradient><linearGradient id="${id}-face" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${earned?'#8f6338':'#4c3958'}"/><stop offset=".5" stop-color="${earned?'#4b3225':'#302636'}"/><stop offset="1" stop-color="${earned?'#6d492b':'#3c2e47'}"/></linearGradient></defs><path d="M50 4 94 29v54L50 108 6 83V29Z" fill="url(#${id}-edge)"/><path d="M50 10 88 32v48l-38 22-38-22V32Z" fill="url(#${id}-face)" stroke="${earned?'#ffe2a355':'#c5a7d02b'}" stroke-width="1.5"/><path d="M50 17 82 36v41L50 95 18 77V36Z" fill="none" stroke="${earned?'#eab46922':'#ac8db71a'}"/><g transform="translate(31 35) scale(1.6)"><path d="${symbol}" fill="${earned&&b.icon==='star'?'#ffd27b':'none'}" stroke="${earned?'#ffd58a':'#ab94b9'}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></g></svg></span>`;}
function profile(){const days=[];let d=today();for(let i=0;i<7;i++){days.unshift(d);d=previousDay(d);}const n=streak(),earned=badges().filter(b=>b.earned).sort((a,b)=>String(state.achievementDates[a.id]||'').localeCompare(String(state.achievementDates[b.id]||''))),latest=earned.at(-1);return `<div class="view profile-view redesigned-profile"><div class="profile-head"><div class="profile-avatar">${esc(state.name[0].toUpperCase())}</div><div><h2>${esc(state.name)}</h2><p>В своём темпе</p></div><a class="icon-btn profile-gear" href="#settings" aria-label="Настройки">${icon('gear')}</a></div><section class="rhythm-panel"><div class="rhythm-landscape" aria-hidden="true"><svg viewBox="0 0 500 170" preserveAspectRatio="none"><path d="M0 150Q120 60 230 125T500 65V170H0Z" fill="#15101c" opacity=".38"/><path d="M0 165Q150 75 340 130T500 100V170H0Z" fill="#18131f" opacity=".6"/></svg></div><div class="rhythm-moon" aria-hidden="true"><svg viewBox="0 0 100 100"><path d="M66 18A32 32 0 1 0 80 74C50 80 38 40 66 18Z" fill="#f5bf60"/><path d="m20 29 2-4 2 4-2 4Zm63 10 2-4 2 4-2 4ZM25 70l2-3 2 3-2 3Z" fill="#f5c471"/></svg></div><h2>Твой ритм</h2><p class="rhythm-number"><strong>${n} ${plural(n,'день','дня','дней')}</strong><span>подряд</span></p><p class="rhythm-caption">${n?'Немного английского каждый день':'Начни с одного хорошего вечера'}</p><div class="activity">${days.map(day=>`<div class="activity-day"><div class="activity-dot ${state.activity[day]?'done':''}" aria-label="${day}: ${state.activity[day]||0} заданий">${state.activity[day]?'✓':''}</div>${new Intl.DateTimeFormat('ru',{weekday:'short',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'))}</div>`).join('')}</div><div class="rhythm-best"><span>Лучшая серия</span><strong>${bestStreak()} ${plural(bestStreak(),'день','дня','дней')}</strong></div></section><section class="profile-showcase"><div class="section-head"><h2>Моя коллекция</h2><a class="text-link" href="#collection">Вся полка ${icon('arrow')}</a></div>${profilePlush.preview()}</section><section class="latest-achievement"><div class="section-head"><h2>Последнее достижение</h2><a class="text-link" href="#achievements">Все достижения ${icon('arrow')}</a></div><a class="achievement-feature" href="#achievements">${achievementArt(latest)}<div><h3>${latest?esc(latest.title):'Всё впереди'}</h3><p>${latest?esc(latest.desc):'Первое достижение появится после урока'}</p></div>${icon('chevron')}</a></section></div>`;}

function subpageHeading(title){return `<div class="subpage-heading"><a class="icon-btn" href="#profile" aria-label="Назад в профиль">${icon('back')}</a><h1>${title}</h1></div>`;}
function settingsPage(){return `<div class="view profile-subpage">${subpageHeading('Настройки')}<section class="panel"><h2>Обучение и оформление</h2><div class="settings-list"><label class="setting"><span>Твоё имя</span><input class="small-input" id="name-input" value="${esc(state.name)}" maxlength="30"></label><label class="setting"><span>Цель на день</span><select class="select" id="goal-select">${[5,10,20].map(n=>`<option value="${n}" ${state.settings.goal===n?'selected':''}>${n} заданий</option>`).join('')}</select></label><label class="setting"><span>Плавные анимации</span><input class="switch" id="motion-setting" type="checkbox" ${state.settings.motion?'checked':''}></label><label class="setting"><span>Звуки проверки</span><input class="switch" id="sound-setting" type="checkbox" ${state.settings.sound?'checked':''}></label><label class="setting"><span>Точка старта</span><select class="select" id="start-select">${[['v1-01','С самого начала'],['v1-17','С приглашений'],['v2-01','Продолжение']].map(([v,n])=>`<option value="${v}" ${state.settings.start===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="setting"><span>Скорость озвучки</span><select class="select" id="speed-select">${SPEEDS.map(v=>[v,speedLabel(v)]).map(([v,n])=>`<option value="${v}" ${state.settings.speed===v?'selected':''}>${n}</option>`).join('')}</select></label></div></section><section class="panel"><h2>Прогресс с тобой</h2><a class="secondary" href="#writing">${icon('edit')} Мои записи из уроков</a><p class="source-note">Сохранение работает на этом устройстве и в этом браузере. Для переноса или резервной копии используй экспорт.</p><div class="settings-list"><button class="secondary" id="export-progress">${icon('download')} Экспортировать прогресс</button><button class="secondary" id="import-progress">${icon('upload')} Восстановить из файла</button><input type="file" id="import-file" accept="application/json,.json" hidden><button class="text-link" id="sources-profile">Учебные источники ${icon('book')}</button><button class="text-link" id="install-help">Установить на телефон ${icon('info')}</button><button class="text-link danger" id="reset-progress">Начать заново</button></div></section></div>`;}
function achievementsPage(){const all=badges();return `<div class="view profile-subpage">${subpageHeading('Достижения')}<p class="achievements-count">Открыто ${all.filter(b=>b.earned).length} из ${all.length}</p><section class="panel"><div class="badges">${all.map(b=>`<div class="badge ${b.earned?'earned':''}" data-badge="${b.id}">${achievementArt(b)}<h3>${esc(b.title)}</h3><p>${esc(b.desc)}</p></div>`).join('')}</div></section></div>`;}
function bindSettings(){document.getElementById('start-select').onchange=e=>{state.settings.start=e.target.value;save();toast('Новая точка старта сохранена');};document.getElementById('name-input').onchange=e=>{state.name=e.target.value.trim()||'Никита';save();};document.getElementById('goal-select').onchange=e=>{state.settings.goal=+e.target.value;save();};document.getElementById('speed-select').onchange=e=>{state.settings.speed=+e.target.value;save();};document.getElementById('motion-setting').onchange=e=>{state.settings.motion=e.target.checked;save();};document.getElementById('sound-setting').onchange=e=>{state.settings.sound=e.target.checked;save();};document.getElementById('export-progress').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='afterhours-progress-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Резервная копия готова');};document.getElementById('import-progress').onclick=()=>document.getElementById('import-file').click();document.getElementById('import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>2000000){toast('Файл слишком большой');return;}try{const incoming=validate(JSON.parse(await f.text()));openModal('Восстановить прогресс?',`<p>Имя: ${esc(incoming.name)}. Пройдено ${Object.keys(incoming.completed).length} эпизодов.</p><p>Текущий прогресс будет заменён. Сначала можно сохранить его через экспорт.</p><button class="primary" id="confirm-import">Восстановить</button>`);document.getElementById('confirm-import').onclick=()=>{state=incoming;session=null;save();modal.close();render();toast('Прогресс восстановлен');};}catch(err){toast('Не удалось прочитать резервную копию: проверь формат файла');}};document.getElementById('sources-profile').onclick=sourcesModal;document.getElementById('install-help').onclick=()=>openModal('Всегда под рукой','<p>На iPhone открой приложение в Safari, нажми «Поделиться», затем «На экран Домой».</p><p>На Android выбери «Установить приложение» в меню браузера.</p><p>После первого открытия основные уроки и изображения доступны без сети. Записи преподавателей по ссылкам требуют интернет.</p>');document.getElementById('reset-progress').onclick=()=>{openModal('Начать заново?',`<p>Уроки, достижения, коллекция и записи будут удалены с этого устройства. Сначала сохрани резервную копию.</p><button class="secondary" id="cancel-reset">Отмена</button> <button class="primary" style="margin-top:12px" id="confirm-reset">Удалить прогресс</button>`);document.getElementById('cancel-reset').onclick=()=>modal.close();document.getElementById('confirm-reset').onclick=()=>{state=fresh();state.seedXP=0;session=null;save();modal.close();location.hash='home';render();};};}
function transition(fn,scroll=false){const token=++routeToken;const view=app.querySelector('.view');if(view&&!document.body.classList.contains('reduce-motion')&&!matchMedia('(prefers-reduced-motion:reduce)').matches){view.classList.add('exiting');setTimeout(()=>{if(token!==routeToken)return;fn();if(scroll)window.scrollTo({top:0,behavior:'instant'});},160);}else{fn();if(scroll)window.scrollTo(0,0);}}
const PAGES=new Set(['home','rules','rule','practice','practice-archive','drill','drill-complete','writing','transfer','practice-complete','lesson','review','complete','speaking','collection','profile','settings','achievements','library','module']);
function render(){const [requested='home',id]=location.hash.slice(1).split('/'),page=PAGES.has(requested)?requested:'home';if(page!==requested)history.replaceState(null,'','#home');document.body.classList.toggle('in-home',page==='home');document.body.classList.toggle('in-lesson',['lesson','review','transfer','drill'].includes(page));document.body.classList.toggle('in-profile',['profile','settings','achievements','collection','writing'].includes(page));stopSpeech();app.querySelectorAll('audio').forEach(a=>a.pause());if(modal.open)modal.close();syncHeader();document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===(['lesson','module','library','complete'].includes(page)?'home':['settings','achievements','collection','writing'].includes(page)?'profile':['rule'].includes(page)?'rules':['transfer','practice-complete','speaking','practice-archive','drill','drill-complete'].includes(page)?'practice':page);a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 if(['rules','rule','practice-archive','drill','drill-complete','writing'].includes(page)){session=null;if(page==='rules')learning.reference();else if(page==='rule')learning.article(id);else if(page==='practice-archive')learning.archive();else if(page==='drill')learning.startDrill(id);else if(page==='drill-complete')learning.recap();else learning.writing();}
 else if(page==='transfer'){session=null;transfer.render(id);}
 else if(page==='practice-complete'){session=null;transfer.complete(id);}
 else if(page==='lesson'){if(!byId.has(id)){location.hash='home';return;}if(!startSession(id)){document.body.classList.remove('in-lesson');renderLessonLock(id);}else renderLesson();}
 else if(page==='review'){const tasks=Object.keys(state.mistakes).map(k=>{const [id,i]=k.split(':');return {l:byId.get(id),i:+i,t:byId.get(id).tasks[+i]};}).slice(0,10);if(!tasks.length){location.hash='practice';return;}startSession(tasks[0].l.id,true,tasks);renderLesson();}
 else if(page==='complete'){try{const r=JSON.parse(sessionStorage.getItem('afterhours.recap'));if(r?.id===id){renderRecap({l:byId.get(id),...r,unlocked:badges().filter(b=>r.unlocked.includes(b.id))});return;}}catch(e){}location.hash='home';}
 else{session=null;app.innerHTML=page==='speaking'?transfer.speakingPage(id):page==='collection'?transfer.collection():page==='profile'?profile():page==='settings'?settingsPage():page==='achievements'?achievementsPage():page==='practice'?practice():page==='library'?library(id):page==='module'?moduleView(id):home();bindCards();app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{app.innerHTML=library(b.dataset.filter);bindLibrary();});if(page==='settings')bindSettings();if(page==='collection')transfer.bindCollection();if(page==='profile')profilePlush.bindCollection();if(page==='speaking')transfer.bindSpeaking();const sources=document.getElementById('about-sources');if(sources)sources.onclick=sourcesModal;}
}
function bindLibrary(){bindCards();app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{app.innerHTML=library(b.dataset.filter);bindLibrary();});}
if('scrollRestoration'in history)history.scrollRestoration='manual';
let renderedRoute=location.hash.slice(1).split('/')[0]||'home',profileScroll=0;
window.addEventListener('hashchange',()=>{const target=location.hash.slice(1).split('/')[0]||'home';if(renderedRoute==='profile')profileScroll=window.scrollY;const restore=target==='profile'&&['settings','achievements','collection'].includes(renderedRoute);transition(()=>{render();renderedRoute=target;window.scrollTo({top:restore?profileScroll:0,behavior:'instant'});},false);});window.addEventListener('pagehide',()=>{if(session)persistSession();stopSpeech();});document.getElementById('xp-link').onclick=()=>location.hash='profile';document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
if('speechSynthesis'in window)speechSynthesis.getVoices();
// Exposed pure functions support reproducible content and persistence validation.
window.Afterhours={norm,matches,validate,lessonGate,completedToday,getState:()=>structuredClone(state),badges,course:C};
let displayedDay=today();function refreshLearningDay(){if(displayedDay===today())return;displayedDay=today();const page=location.hash.slice(1).split('/')[0]||'home';if(['home','library','module','profile'].includes(page)||page==='lesson'&&!session)render();}
window.addEventListener('focus',refreshLearningDay);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshLearningDay();});setInterval(refreshLearningDay,60000);
render();
})();
