'use strict';
// Original practice scenarios. Course remains the unchanged, source-based curriculum.
(()=>{
const gap=(prompt,display,answer,rule)=>({type:'gap',prompt,display,answer,rule});
const order=(prompt,answer,rule)=>({type:'order',prompt,answer,rule});
const fix=(display,answer,rule)=>({type:'fix',prompt:'Исправь реплику целиком, сохранив её смысл.',display,answer,rule});
const listen=(audio,question,options,correct,rule)=>({type:'listen',prompt:question,audio,options,answer:options[correct],rule});
const choice=(line,label,reply,task,result,effects={},flags={},cost=0,need=null)=>({line,label,reply,task,result,effects,flags,cost,need});
const upgrades=[
{id:'seating',title:'Уголок у окна',desc:'Два дополнительных места. +2 к постоянным гостям, +5 к репутации.',xp:450,cash:100,maintenance:4,icon:'chair',effects:{guests:2,rep:5},tag:'Новые места'},
{id:'espresso',title:'Кофемашина',desc:'Капучино в меню. +18 £ к выручке за смену; обслуживание 6 £.',xp:600,cash:180,maintenance:6,icon:'coffee',effects:{rep:3},revenue:18,tag:'Капучино'},
{id:'acoustic',title:'Тихий зал',desc:'Акустические панели. Нагрузка команды снижается на 12; соседям становится тише.',xp:400,cash:90,maintenance:0,icon:'sound',effects:{stress:-12,rep:4},tag:'Тихий зал'},
{id:'training',title:'Обучение команды',desc:'Нагрузка −15. В напряжённые смены штраф за перегрузку вдвое меньше.',xp:650,cash:100,maintenance:3,icon:'team',effects:{stress:-15,trust:4},tag:'Сильная команда'},
{id:'kitchen',title:'Небольшая кухня',desc:'Свежие сэндвичи. +28 £ к выручке, обслуживание 10 £; появляются заказы на обеды.',xp:950,cash:220,maintenance:10,icon:'food',effects:{stress:5},revenue:28,requires:['espresso'],tag:'Обеденное меню'},
{id:'library',title:'Книжная полка',desc:'Книжный клуб: +3 гостя и +6 к репутации. Без расходов на обслуживание.',xp:550,cash:80,maintenance:0,icon:'book',effects:{guests:3,rep:6},tag:'Книжный клуб'},
{id:'terrace',title:'Вечерняя терраса',desc:'Ещё +4 гостя, +6 репутации. Обслуживание 12 £; больше работы для команды.',xp:1100,cash:250,maintenance:12,icon:'leaf',effects:{guests:4,rep:6,stress:8},requires:['seating'],tag:'Терраса'},
{id:'roaster',title:'Своя обжарка',desc:'+35 £ к выручке, обслуживание 12 £. Помогает сократить зависимость от поставщика.',xp:1400,cash:400,maintenance:12,icon:'beans',effects:{rep:8,stress:5},revenue:35,requires:['espresso','training'],tag:'Своя обжарка'}
];
const episodes=[
{id:'opening',xp:0,title:'Ключи от вечера',who:'Элли',role:'Бариста',intro:'Первый вечер. У дверей уже ждут соседи, а ты ещё выбираешь, каким будет это место.',npc:'We can open tonight, but we only have enough coffee for a small crowd. What do you want to do?',task:order('Уточни запас: «У нас достаточно кофе на сегодняшний вечер».','We have enough coffee for tonight.','enough + существительное; for tonight — на сегодня.'),choices:[
choice('Let’s invite the neighbours.','Камерное открытие','I can make a small welcome menu.',gap('Подтверди план Элли: одно слово.','We _____ inviting our neighbours tonight.','are','Действие, запланированное на ближайшее время: be + -ing.'),'Соседи стали первыми постоянными гостями. Шумного открытия не было, зато появился костяк сообщества.',{guests:3,rep:6,stress:3},{identity:'local'}),
choice('Let’s advertise a big opening.','Громкое открытие','More people means a longer queue.',gap('Спроси об очереди: одно слово.','How long _____ people have to wait?','will','Вопрос о будущем: will + подлежащее + глагол.'),'Людей много, касса выросла. Элли едва справилась: этот темп ещё аукнется.',{cash:100,guests:2,rep:2,stress:18},{identity:'busy'},40),
choice('Let’s open quietly and test the service.','Проверить работу','We can practise before we invite everyone.',gap('Объясни цель: одно слово.','We want _____ test the service first.','to','want to + начальная форма глагола.'),'Ты обкатал обслуживание без ажиотажа. Гостей пока меньше, команда готова лучше.',{stress:-8,rep:3},{identity:'careful'})]},
{id:'delivery',xp:0,title:'Не тот заказ',who:'Дэниел',role:'Поставщик',intro:'В коробках чай вместо кофе. Машина поставщика уехала, до открытия меньше часа.',npc:'I’m sorry. We sent the wrong boxes. I can replace them tomorrow, or send a courier today.',task:listen('The courier costs forty pounds. A replacement tomorrow is free.','Что стоит 40 £?',['Доставка курьером сегодня','Замена завтра','Сам чай'],0,'today — сегодня; tomorrow — завтра. Условия нужно различать до выбора.'),choices:[
choice('Please send a courier today.','Срочно заменить','I’ll arrange it. The courier will be there before opening.',gap('Спроси о сроке: одно слово.','Will the courier _____ before we open?','arrive','После will — глагол в начальной форме.'),'Кофе приехал вовремя, но за срочность ты заплатил. Поставщик оценил спокойный разговор.',{trust:8,rep:3},{supplier:'partner'},40),
choice('We’ll serve tea today. Replace the order tomorrow.','Сделать вечер чая','I’ll include a small discount next time.',gap('Объясни замену: одно слово.','We are serving tea _____ of coffee today.','instead','instead of — вместо.'),'Ты сохранил деньги, но часть любителей кофе ушла. Зато поставщик обещал скидку.',{cash:-20,guests:-1,trust:14,rep:-3},{supplier:'flexible'}),
choice('Please refund the order. We’ll find another supplier.','Разорвать договор','I can refund it, but our agreement will end.',gap('Подтверди поиск: одно слово.','We _____ looking for another supplier now.','are','Present Continuous: are + looking.'),'Деньги возвращены. Теперь придётся договариваться с новым поставщиком без старых условий.',{cash:45,trust:-25,stress:7},{supplier:'broken'})]},
{id:'review',xp:350,title:'Первый отзыв',who:'Майя',role:'Посетительница',intro:'Гостья написала, что ждала слишком долго. Вечер уже закончился, отзыв видят все.',npc:'The coffee was lovely, but I waited twenty minutes. Can you explain what happened?',task:fix('We was very busy last night.','We were very busy last night.','В прошлом: we / you / they were; I / he / she was.'),choices:[
choice('You’re right. Let me offer you a coffee.','Признать и компенсировать','Thank you for taking it seriously.',gap('Пригласи её снова: одно слово.','Would you like _____ come back tomorrow?','to','would like to + глагол.'),'Майя обновила отзыв и решила вернуться. Бесплатный кофе стоил денег, но вернул доверие.',{rep:10,guests:2},{review:'recovered'},25),
choice('We’ll change the way we take orders.','Исправить процесс','I’d like to see whether it gets better.',gap('Сообщи об изменении: одно слово.','We will _____ a separate queue for takeaway orders.','create','После will используется create, а не creates.'),'Обещание осталось публичным. Когда очередь появится снова, гости проверят, сдержал ли ты слово.',{rep:4,stress:-6},{review:'promise'}),
choice('It was our first night. Please give us time.','Объяснить без компенсации','I understand, but waiting is still a problem.',gap('Признай трудность: одно слово.','Waiting _____ frustrating for our guests.','is','Герундий waiting как подлежащее требует is.'),'Ты не потратил деньги. Отзыв остался сдержанным, а проблема очереди никуда не делась.',{rep:-4,stress:3},{review:'unresolved'})]},
{id:'menu',xp:650,title:'Цена одного решения',who:'Элли',role:'Бариста',intro:'Пора выбрать направление меню. Нельзя одновременно быть самым дешёвым и самым необычным кафе района.',npc:'Customers keep asking about our menu. Should we focus on price, quality, or seasonal drinks?',task:gap('Заполни сравнение: одно слово.','This coffee is more expensive _____ that one.','than','Сравнение: more expensive than.'),choices:[
choice('Let’s keep the menu affordable.','Доступные цены','We’ll sell more, but earn less on each drink.',gap('Опиши цены: одно слово.','Our prices are _____ than theirs.','lower','low → lower; сравниваем цены.'),'Гостей больше, маржа ниже. Будущие дорогие поставки будет сложнее переложить на покупателей.',{guests:4,cash:-30,rep:3},{menu:'value'}),
choice('Let’s focus on quality.','Качество важнее','We need better beans and consistent preparation.',gap('Спроси о количестве: одно слово.','How _____ coffee do we need each week?','much','coffee как масса — неисчисляемое; how much.'),'Средний чек вырос. Гости теперь ждут стабильного качества и болезненнее реагируют на замену кофе.',{cash:40,rep:6,stress:5},{menu:'quality'},60),
choice('Let’s try a seasonal menu.','Сезонные напитки','We’ll have to explain the new drinks clearly.',gap('Опиши новинку: одно слово.','This drink _____ cinnamon and orange in it.','has','This drink / it → has.'),'Меню привлекло любопытных гостей. Новинки требуют подготовки и объяснений.',{guests:2,rep:5,stress:8},{menu:'seasonal'},30)]},
{id:'supplier-return',xp:1000,title:'Цена доверия',who:'Дэниел',role:'Поставщик',intro:'Условия новой партии зависят от того, как ты решил проблему с коробками.',variants:[{when:{supplier:'broken'},npc:'Your new supplier cancelled. I can help, but I need payment in advance.',intro:'Новый поставщик отменил доставку. Дэниел готов вернуться, но требует предоплату.'},{when:{supplier:'flexible'},npc:'You helped us last time. I can offer a discount if you commit to a larger order.',intro:'За гибкость Дэниел предложил скидку. Взамен просит заказать большую партию.'}],npc:'I can offer a long-term contract. Would you prefer a fixed price or flexible weekly orders?',task:order('Спроси: «Можем ли мы изменить заказ на следующей неделе?»','Can we change the order next week?','Can + подлежащее + глагол в вопросе.'),choices:[
choice('Let’s agree on a fixed price.','Долгий договор','The price stays the same, even when costs rise.',gap('Уточни срок: одно слово.','How long does the agreement _____?','last','После does — last в начальной форме.'),'Цена зафиксирована. Во время следующего скачка цен договор защитит кафе.',{trust:12,stress:-3},{contract:'fixed'},70),
choice('We’d like flexible weekly orders.','Гибкий объём','That works, but prices may change.',gap('Подтверди частоту: одно слово.','We order coffee once _____ week.','a','once a week — раз в неделю.'),'Можно менять объём без обязательств. Риск повышения цены остаётся на тебе.',{trust:6},{contract:'flex'}),
choice('We’ll buy from several suppliers.','Диверсификация','Then I can’t offer the same discount.',gap('Объясни причину: одно слово.','We need another option _____ a delivery is late.','if','if — если; условие возможной задержки.'),'Ты снизил зависимость, но потерял скидку и добавил себе работы.',{trust:-8,stress:8},{contract:'multiple'},30)]},
{id:'rush',xp:1400,title:'Очередь до двери',who:'Элли',role:'Бариста',intro:'После обеда очередь растёт. Вспоминают и твой ответ на первый отзыв.',variants:[{when:{review:'promise'},intro:'Гости вспоминают обещанную очередь для заказов навынос. Сейчас станет ясно, чего стоило обещание.'}],npc:'We have twelve people waiting. I can work faster, but I’m already making mistakes.',task:listen('Two customers have already left. The others are still waiting outside.','Сколько гостей ушло?',['Двое','Двенадцать','Все'],0,'already left — уже ушли; still waiting — всё ещё ждут.'),choices:[
choice('Let’s separate takeaway orders from table service.','Разделить поток','I’ll put a clear sign by the counter.',gap('Объясни правило: одно слово.','Please _____ here if you want a takeaway coffee.','wait','В просьбе: please + начальная форма глагола.'),'Потоки разделены. Публичное обещание выполнено, нагрузка уменьшилась.',{rep:7,stress:-8},{queue:'split'},35),
choice('Let’s stop taking orders for ten minutes.','Пауза на десять минут','We can catch up and explain the delay.',gap('Назови время: одно слово.','We will reopen _____ ten minutes.','in','in ten minutes — через десять минут.'),'Несколько гостей ушли, зато команда вернула контроль над заказами.',{guests:-1,stress:-15,rep:2},{queue:'pause'}),
choice('Keep taking orders. We can handle it.','Работать на пределе','I’ll try, but we need a better plan next time.',gap('Исправь форму: одно слово.','Ellie _____ doing her best right now.','is','Элли / she → is doing.'),'Касса выросла, но ошибок и усталости стало больше. Элли запомнила этот выбор.',{cash:85,stress:22,rep:-5},{queue:'push'})]},
{id:'allergy',xp:1800,title:'Это точно без орехов?',who:'Том',role:'Посетитель',intro:'Гость спрашивает о составе десерта. На упаковке нет полной информации: гадать нельзя.',npc:'I have a nut allergy. Do you know whether this cake contains nuts?',task:order('Скажи честно: «Я не уверен в ингредиентах».','I am not sure about the ingredients.','be sure about — быть уверенным в чём-либо.'),choices:[
choice('I’ll check with the bakery before serving it.','Проверить состав','Thank you. I can wait for a clear answer.',gap('Объясни действие: одно слово.','I am _____ the bakery now.','calling','Сейчас: am + calling.'),'Пекарня подтвердила состав. Гость оценил проверку, но обслуживание заняло время.',{rep:8,stress:3},{safety:'checked'}),
choice('We can offer a sealed drink instead.','Безопасная альтернатива','That would be fine. I’ll skip the cake.',gap('Уточни выбор: одно слово.','Would you prefer tea _____ coffee?','or','Выбор между вариантами: or.'),'Ты не продавал продукт с неизвестным составом. Чек меньше, доверие сохранено.',{cash:-10,rep:5},{safety:'alternative'}),
choice('I can’t confirm the ingredients, so I won’t sell it.','Отказаться от продажи','I appreciate your honesty.',gap('Объясни отказ: одно слово.','We cannot _____ its ingredients today.','confirm','После cannot — глагол без to.'),'Продажа потеряна. Честный отказ сохранил репутацию и побудил пересмотреть карточки состава.',{cash:-20,rep:7,stress:-2},{safety:'strict'})]},
{id:'booking',xp:2300,title:'Стол на пятницу',who:'Майя',role:'Организатор встречи',intro:'Шесть человек хотят прийти в пятницу. Большой заказ может вытеснить постоянных гостей.',npc:'Could we book a table for six on Friday evening? We’d like to stay for two hours.',task:gap('Уточни время: одно слово.','What time _____ you like to arrive?','would','What time would you like… — вежливый вопрос.'),choices:[
choice('We can reserve a table with a deposit.','Бронь с предоплатой','That’s fair. Please send the details.',gap('Назови условие: одно слово.','The deposit must be paid _____ Friday.','before','before Friday — до пятницы.'),'Предоплата снизила риск отмены. Часть мест занята, но заказ предсказуем.',{cash:65,stress:4},{booking:'deposit'}),
choice('You’re welcome, but we can’t reserve seats.','Без бронирования','We’ll try to arrive early, then.',gap('Объясни принцип: одно слово.','Seats are available on a first-come, first-served _____.','basis','on a … basis — по такому принципу.'),'Места остались доступными всем. Группа может выбрать другое кафе.',{rep:2,guests:1},{booking:'walkin'}),
choice('We’ll reserve the whole corner for you.','Выделить уголок','Wonderful. We’ll bring our friends.',gap('Подтверди число: одно слово.','We have reserved a table _____ six.','for','a table for six — стол на шестерых.'),'Группа довольна, но постоянным гостям осталось меньше мест.',{cash:100,guests:2,stress:8,rep:-2},{booking:'exclusive'},0,{upgrade:'seating'})]},
{id:'team',xp:2800,title:'Человек за стойкой',who:'Элли',role:'Бариста',intro:'Элли просит поговорить после смены. Разговор зависит от накопленной нагрузки.',stressIntro:'После нескольких тяжёлых смен Элли уже думает об уходе. Одного обещания будет мало.',npc:'I enjoy working here, but I need a schedule I can rely on. Can we change something?',task:fix('She don’t have enough time to rest.','She does not have enough time to rest.','She doesn’t / does not + начальная форма have.'),choices:[
choice('Let’s hire help for the busiest hours.','Подкрепление в пик','That would make a real difference.',gap('Опиши график: одно слово.','The new assistant will work _____ the busiest hours.','during','during — в течение.'),'Помощник разгрузил Элли. Деньги ушли на найм, зато команда держится увереннее.',{stress:-25,rep:4},{team:'supported'},100),
choice('Let’s reduce our opening hours.','Сократить часы','We’ll lose some sales, but we can do the job properly.',gap('Объясни изменение: одно слово.','We will close one hour _____ than before.','earlier','early → earlier; сравнение времени.'),'Выручка уменьшилась, зато появился устойчивый график.',{stress:-18,cash:-35},{team:'balanced'}),
choice('Let’s keep the hours and offer a bonus.','Премия без смены графика','I appreciate it, but I still need proper rest.',gap('Признай проблему: одно слово.','Money does not _____ the problem completely.','solve','does not + solve; solve the problem.'),'Премия помогла ненадолго. Нагрузка осталась, и при следующем пике усталость вернётся.',{stress:-4,rep:2},{team:'bonus'},50)]},
{id:'noise',xp:3300,title:'Соседи слышат всё',who:'Оливер',role:'Сосед',intro:'Сосед живёт над кафе. Поздние разговоры мешают ему спать.',npc:'I like your café, but the noise travels upstairs after nine. Can we find a compromise?',task:order('Спроси: «Когда шум становится проблемой?»','When does the noise become a problem?','When does + подлежащее + начальная форма глагола.'),choices:[
choice('We’ll keep the café quiet after nine.','Тихие вечера','That would help. I’ll let you know if it improves.',gap('Обозначь границу: одно слово.','We will lower the music _____ nine o’clock.','after','after — после.'),'Вы договорились о тихом режиме. Часть вечерних гостей стала приходить раньше.',{rep:7,cash:-15},{noise:'quiet'}),
choice('We’ve improved the acoustics. Let’s test them together.','Проверить шумоизоляцию','Good idea. I’ll listen from upstairs.',gap('Предложи проверку: одно слово.','Let’s _____ the sound level together.','check','Let’s + начальная форма.'),'Панели сработали, сосед услышал разницу. Поздние встречи можно сохранить.',{rep:10,guests:2},{noise:'insulated'},0,{upgrade:'acoustic'}),
choice('We’ll stop evening events for now.','Приостановить события','Thank you. We can review the situation later.',gap('Уточни срок: одно слово.','We will pause events _____ we find a better solution.','until','until — до тех пор, пока.'),'Тишина вернулась. Вечерние события потеряли доход и часть аудитории.',{rep:4,guests:-2,cash:-25,stress:-8},{noise:'paused'})]},
{id:'club',xp:3900,title:'Клуб по четвергам',who:'Майя',role:'Организатор',intro:'Майя хочет сделать встречи регулярными. Теперь нужно решить, кому и на каких условиях отдавать пространство.',npc:'People loved our last meeting. Could we make it a weekly event?',task:listen('We’d like to meet every Thursday, from seven to eight.','Когда предлагают встречаться?',['По четвергам, с семи до восьми','Каждый день после восьми','По пятницам, с шести до семи'],0,'every Thursday — каждый четверг; from … to … — с … до ….'),choices:[
choice('Let’s start a small book club.','Книжные встречи','We’ll choose a short book and invite the neighbours.',gap('Согласуй периодичность: одно слово.','The club will meet _____ Thursdays.','on','on + день недели во множественном числе.'),'Вокруг книжной полки сложилось сообщество. Доход скромный, гости возвращаются чаще.',{guests:4,rep:7,stress:3},{club:'books'},0,{upgrade:'library'}),
choice('Let’s charge a small booking fee.','Платная бронь клуба','I can include it in the members’ contributions.',gap('Уточни оплату: одно слово.','Does the fee _____ drinks?','include','Does + подлежащее + include.'),'Встречи стали приносить предсказуемые деньги. Бесплатный формат потерял часть участников.',{cash:70,guests:1,stress:4},{club:'paid'}),
choice('Let’s keep it informal for now.','Свободные встречи','Then people can join whenever they like.',gap('Объясни доступ: одно слово.','Anyone can _____ us.','join','can + join без to.'),'Вход свободный, но организационные вопросы приходят прямо к стойке.',{guests:3,stress:9},{club:'open'})]},
{id:'price-rise',xp:4500,title:'Дорожает не только кофе',who:'Дэниел',role:'Поставщик',intro:'Цена зерна выросла. Итог зависит от ранее выбранного договора.',variants:[{when:{contract:'fixed'},npc:'Prices have risen, but your fixed-price contract still protects this order.',intro:'Фиксированная цена защитила текущую партию. Можно использовать запас времени для решения.'}],npc:'Our costs have increased. The next delivery will be more expensive unless we change something.',task:fix('The new beans are expensiver than the old ones.','The new beans are more expensive than the old ones.','Длинное expensive: more expensive, не expensiver.'),choices:[
choice('We’ll raise prices slightly and explain why.','Небольшое повышение','A clear explanation is better than a surprise.',gap('Объясни причину: одно слово.','We are changing prices _____ our costs have increased.','because','because вводит причину.'),'Маржа восстановилась. Для доступного меню повышение особенно чувствительно.',{cash:45,guests:-1,rep:-2},{pricing:'raise'}),
choice('We’ll absorb the cost for now.','Сохранить цены','That protects your customers, but watch your cash.',gap('Назови решение: одно слово.','Our prices will _____ the same for now.','stay','will stay the same — останутся прежними.'),'Гости сохранили привычный чек. Расход лег на кафе; фиксированный договор смягчил удар.',{rep:6,cash:-60},{pricing:'absorb'}),
choice('We’ll use our own roast for the house blend.','Собственная смесь','Then you’ll depend less on my deliveries.',gap('Опиши независимость: одно слово.','We will roast our _____ coffee.','own','our own — наш собственный.'),'Обжарка помогла удержать качество и цену. Работы прибавилось, зависимость уменьшилась.',{cash:55,stress:5,trust:-3,rep:5},{pricing:'roast'},0,{upgrade:'roaster'})]},
{id:'rain',xp:5100,title:'Вечер под дождём',who:'Том',role:'Постоянный гость',intro:'Начался сильный дождь. Люди заходят переждать его, не все готовы что-то купить.',npc:'Could we stay inside until the rain stops? Some of us haven’t ordered anything.',task:order('Скажи: «Вы можете остаться, пока дождь не закончится».','You can stay until the rain stops.','После until в условии будущего: Present Simple — stops.'),choices:[
choice('Of course. We’ll make room for everyone.','Пустить всех','That’s kind. I’ll help move the chairs.',gap('Предложи помощь: одно слово.','Could you _____ me move this table?','help','help me move — помочь мне передвинуть.'),'Кафе стало убежищем для района. Новые гости запомнили вечер, команде пришлось потесниться.',{guests:4,rep:8,stress:10,cash:-20},{rain:'shelter'}),
choice('We can share tables if everyone agrees.','Общие столы','I’ll ask the people by the window first.',gap('Спроси согласие: одно слово.','Do you mind _____ this table?','sharing','Do you mind + -ing.'),'Все разместились, а часть незнакомцев разговорилась. Дополнительные места помогли справиться.',{guests:2,rep:5,stress:4},{rain:'shared'}),
choice('We need to keep some tables for customers.','Оставить места заказам','I understand. Let us know when a table is free.',gap('Объясни приоритет: одно слово.','We need to keep a few tables _____ for customers.','available','keep … available — оставить доступным.'),'Обслуживание не просело. Несколько соседей нашли укрытие в другом месте.',{cash:35,rep:-3,stress:-3},{rain:'limited'})]},
{id:'repair',xp:5800,title:'Машина замолчала',who:'Рэй',role:'Мастер',intro:'Кофемашина перестала работать перед сменой. Есть быстрый ремонт и более надёжное обслуживание.',npc:'I can make it run today, but replacing the worn part would be safer in the long term.',task:listen('A quick repair costs sixty pounds. Replacing the part costs one hundred and twenty.','Сколько стоит замена детали?',['120 £','60 £','180 £'],0,'quick repair — быстрый ремонт; replacing the part — замена детали.'),choices:[
choice('Replace the part, please.','Надёжный ремонт','It will take longer, but the machine will be dependable.',gap('Уточни длительность: одно слово.','How long _____ the repair take?','will','How long will … take? — сколько времени займёт?' ),'Деталь заменена. В финальный напряжённый вечер эта инвестиция снизит риск срыва.',{stress:-5,rep:3},{repair:'reliable'},120),
choice('Do the quick repair for now.','Быстро вернуть работу','It will work, but please don’t push it too hard.',gap('Обозначь ограничение: одно слово.','We should not _____ it too hard.','push','should not + push.'),'Ты сэкономил время и деньги, но оставил риск поломки под большой нагрузкой.',{cash:20,stress:4},{repair:'temporary'},60),
choice('We’ll serve tea and filter coffee today.','Пережить без ремонта','All right. Call me when you’re ready.',gap('Сообщи замену: одно слово.','We can still _____ filter coffee today.','serve','can still serve — всё ещё можем подавать.'),'Платежа нет, часть гостей ушла без привычного напитка. Поломка осталась нерешённой.',{cash:-30,rep:-4},{repair:'deferred'})]},
{id:'critic',xp:6500,title:'Заметка о районе',who:'Джун',role:'Журналистка',intro:'Местное издание выбирает места для обзора. Что именно ты хочешь рассказать о кафе?',npc:'I’m writing about places that bring the neighbourhood together. What makes your café different?',task:fix('People comes here to meet their neighbours.','People come here to meet their neighbours.','People — множественное число; come без -s.'),choices:[
choice('We’re building a place where people know each other.','Рассказать о сообществе','Tell me about someone who found friends here.',gap('Назови историю: одно слово.','Maya _____ her neighbours at our first meeting.','met','Прошедшая форма meet — met.'),'В статье появились истории гостей. Ранние решения о соседях и укрытии от дождя усилили эффект.',{rep:9,guests:2},{press:'community'}),
choice('We focus on carefully prepared coffee.','Рассказать о кофе','I’d like to taste your house coffee, then.',gap('Опиши качество: одно слово.','Every cup is prepared _____.','carefully','Как приготовлено? Наречие carefully.'),'Статья привлекла ценителей кофе. Они заметят и качество меню, и нерешённую поломку.',{cash:45,rep:5},{press:'coffee'}),
choice('We’re still learning. Visit us again in a month.','Отложить обзор','I appreciate the honesty. I’ll keep in touch.',gap('Предложи возвращение: одно слово.','Please _____ back next month.','come','come back — вернуться.'),'Ты избежал обзора раньше времени. Поток гостей не вырос, зато команда получила передышку.',{stress:-8,rep:2},{press:'later'})]},
{id:'lunch',xp:7200,title:'Двадцать обедов',who:'Майя',role:'Заказчик',intro:'Офис рядом хочет заказать обеды. Заказ прибыльный, но возможностей кухни может не хватить.',npc:'Our office needs twenty lunches on Tuesday. Can you deliver them all by noon?',task:gap('Уточни крайний срок: одно слово.','Do you need them _____ twelve o’clock?','by','by noon / by twelve — не позднее полудня.'),choices:[
choice('We can prepare a limited lunch menu.','Принять с простым меню','I’ll send you the dietary requirements today.',gap('Запроси состав: одно слово.','Please send us a list _____ dietary requirements.','of','a list of — список чего-либо.'),'Небольшая кухня справилась с ограниченным меню. Заказ принёс деньги, команда устала.',{cash:170,stress:13,rep:5},{lunch:'accepted'},40,{upgrade:'kitchen'}),
choice('We can provide drinks, but not all the lunches.','Взять часть заказа','That helps. I’ll arrange food elsewhere.',gap('Уточни напитки: одно слово.','How many drinks _____ you need?','do','How many + исчисляемое; do you need?' ),'Ты взял посильную часть работы. Доход меньше, зато сроки выдержаны.',{cash:65,stress:4,rep:3},{lunch:'partial'}),
choice('We can’t guarantee delivery by noon.','Честно отказаться','Thanks for telling me before we made plans.',gap('Объясни ограничение: одно слово.','We do not have enough time _____ prepare everything.','to','enough time to + глагол.'),'Заказ ушёл другому месту. Отношения сохранились, команда не перегружена.',{rep:4,stress:-5},{lunch:'declined'})]},
{id:'burnout',xp:8000,title:'Цена успеха',who:'Элли',role:'Бариста',intro:'Заказов становится больше. Элли хочет понять, чего ты ждёшь от следующего месяца.',stressIntro:'Элли прямо говорит, что такой график больше не выдержит. Накопленные решения требуют перемен.',npc:'Are we trying to grow as fast as possible, or do we want a café we can keep running for years?',task:order('Скажи: «Нам нужен план, который работает для всех».','We need a plan that works for everyone.','a plan that works — план, который работает; that связывает части.'),choices:[
choice('Let’s train the team and grow slowly.','Устойчивый рост','Then we can take on more without losing control.',gap('Назови цель: одно слово.','We want to grow _____ losing quality.','without','without + -ing.'),'Обученная команда выстроила устойчивую работу. Это поможет на большом вечере.',{stress:-20,rep:7},{growth:'steady'},0,{upgrade:'training'}),
choice('Let’s keep the café small for now.','Остаться небольшими','I’d rather do a smaller job well.',gap('Сравни размер: одно слово.','A smaller café is easier _____ manage.','to','easier to manage — легче управлять.'),'Ты сознательно ограничил рост. Касса скромнее, отношения с командой крепче.',{stress:-16,cash:-20,rep:4},{growth:'small'}),
choice('Let’s take the opportunity and expand now.','Ускорить рост','We’ll need to cope with a lot more work.',gap('Предупреди нагрузку: одно слово.','We will need _____ help than before.','more','more help — больше помощи.'),'Ты выбрал быстрый рост. Денег и внимания больше, запас сил команды уменьшился.',{cash:120,guests:4,stress:22},{growth:'fast'},50)]},
{id:'festival',xp:8800,title:'Фестиваль на улице',who:'Оливер',role:'Организатор района',intro:'На улице готовят вечерний фестиваль. Формат участия зависит от твоего пространства и команды.',npc:'We’d love your café to take part. Could you serve drinks outside, host a gathering, or support us another way?',task:listen('The festival starts at six, but all stalls must be ready by half past five.','Когда всё должно быть готово?',['К 17:30','К 18:00','После 18:30'],0,'Starts at six — начинается в шесть; ready by half past five — готово к половине шестого.'),choices:[
choice('We’ll serve drinks on our terrace.','Открыть террасу','Wonderful. We’ll add you to the festival map.',gap('Подтверди готовность: одно слово.','We will be ready _____ half past five.','by','by — не позднее указанного срока.'),'Терраса привлекла новых гостей. Большая смена проверила команду и оборудование.',{cash:160,guests:4,stress:15,rep:7},{festival:'terrace'},60,{upgrade:'terrace'}),
choice('We’ll host a small gathering inside.','Встреча внутри','Let’s make sure it won’t disturb the neighbours.',gap('Уточни тишину: одно слово.','We will keep the music _____.','quiet','keep + объект + прилагательное.'),'Камерная встреча укрепила сообщество. Реакция соседей зависит от старой договорённости.',{cash:60,rep:6,stress:7},{festival:'inside'},20),
choice('We’ll provide drinks for the volunteers.','Помочь организаторам','They’ll really appreciate that.',gap('Назови получателей: одно слово.','These drinks are _____ the volunteers.','for','for — для кого-либо.'),'Ты помог фестивалю без массового потока в кафе. Благодарность есть, больших продаж нет.',{cash:-40,rep:8,stress:2},{festival:'support'},0)]},
{id:'inspection',xp:9600,title:'Обещания на бумаге',who:'Рэй',role:'Консультант',intro:'Перед следующим сезоном нужно проверить, совпадает ли реальная работа с твоими обещаниями.',npc:'Let’s review what you promised your customers and staff. Which problem should we deal with first?',task:fix('We have make several promises this season.','We have made several promises this season.','Present Perfect: have + третья форма; make → made.'),choices:[
choice('Let’s prioritise reliable equipment.','Надёжность оборудования','Good. A temporary repair isn’t a long-term plan.',gap('Назови уже сделанное: одно слово.','We have _____ the worn part.','replaced','have + replaced: действие с результатом сейчас.'),'Ты довёл обслуживание до конца. Следующий сезон начинается без старой поломки.',{stress:-8,rep:4},{audit:'equipment',repair:'reliable'},90),
choice('Let’s prioritise the team’s schedule.','График команды','A dependable schedule will prevent another crisis.',gap('Подтверди график: одно слово.','Everyone _____ when their shift starts.','knows','Everyone — единственное число; knows.'),'У команды появились ясные смены. Недовольство не исчезло мгновенно, но стало меньше.',{stress:-20,rep:3},{audit:'team',team:'supported'},45),
choice('Let’s prioritise clear information for guests.','Информация для гостей','Ingredients, waiting times, and prices should all be clear.',gap('Назови обязанность: одно слово.','Guests should _____ what they are ordering.','know','should + know без to.'),'Появились карточки состава и честные сроки ожидания. Споры у стойки стали реже.',{rep:8,stress:-4},{audit:'guests'},0)]},
{id:'finale',xp:10500,title:'Последний вечер сезона',who:'Элли',role:'Бариста',intro:'Пришло время выбрать, каким кафе войдёт в следующий сезон. Итог сложился из всех предыдущих решений.',npc:'We’ve built something real. What do you want people to remember about this place?',task:order('Скажи: «Я горжусь тем, что мы построили вместе».','I am proud of what we have built together.','be proud of — гордиться; have built — построили к настоящему моменту.'),choices:[
choice('A place where neighbours become friends.','Дом для района','Then let’s keep the community at the centre of our decisions.',gap('Подтверди приоритет: одно слово.','Our guests are more than just _____.','customers','customers — покупатели / клиенты.'),'Ты выбрал путь сообщества. Насколько он удался, показывают постоянные гости, доверие и обещания.',{rep:5},{ending:'community'}),
choice('A café known for exceptional coffee.','Мастерская кофе','Then consistency matters as much as ambition.',gap('Подчеркни качество: одно слово.','Quality matters _____ much as ambition.','as','as much as — в такой же степени, как.'),'Ты выбрал путь мастерства. Итог зависит от меню, оборудования и того, как ты справлялся со сбоями.',{rep:4},{ending:'craft'}),
choice('A business that takes care of its people.','Устойчивое дело','That means watching our finances and our working hours.',gap('Подчеркни баланс: одно слово.','We need to look _____ our team.','after','look after — заботиться о.'),'Ты выбрал устойчивость. Финансы и нагрузка покажут, удалось ли превратить её в реальность.',{stress:-8},{ending:'sustainable'})]}
];
window.CAFE_CONTENT={version:1,upgrades,episodes};
})();
