'use strict';
// Pure deterministic game reducer. All balances are derived from the journal.
(()=>{
const D=window.CAFE_CONTENT,upgrades=new Map(D.upgrades.map(u=>[u.id,u])),events=new Map(D.episodes.map((e,i)=>[e.id,{...e,index:i}]));
const fresh=()=>({version:1,log:[],active:null,tab:'development'});
const initial=()=>({cash:300,rep:52,trust:50,stress:18,guests:6,spent:0,turn:0,owned:[],flags:{},history:[]});
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
function affect(s,effects){for(const [key,value] of Object.entries(effects||{})){if(['cash','rep','trust','stress','guests'].includes(key))s[key]+=value;}for(const key of ['rep','trust','stress'])s[key]=clamp(s[key],0,100);s.guests=clamp(s.guests,0,200);}
function details(event,s){const variant=event.variants?.find(v=>Object.entries(v.when).every(([key,value])=>s.flags[key]===value));return {...event,...variant,intro:s.stress>=65&&event.stressIntro?event.stressIntro:variant?.intro||event.intro};}
function access(event,s,xp,completed){if(s.turn!==event.index)return 'Сначала заверши предыдущую историю';if(completed<1)return 'Заверши хотя бы один эпизод английского';const lessons=Math.ceil((event.index+1)*82/D.episodes.length);if(xp<event.xp&&completed<lessons)return `Нужно ${event.xp} общего XP или ${lessons} пройденных эпизодов`;return '';}
function canBuy(u,s,xp){if(!u)return 'Неизвестное улучшение';if(s.owned.includes(u.id))return 'Уже установлено';const missing=(u.requires||[]).filter(id=>!s.owned.includes(id));if(missing.length)return 'Сначала: '+missing.map(id=>upgrades.get(id).title).join(', ');if(xp-s.spent<u.xp)return `Не хватает ${u.xp-(xp-s.spent)} XP`;if(s.cash<u.cash)return `Нужно ${u.cash} £ в кассе`;return '';}
function canChoose(c,s){if(!c)return 'Неизвестный выбор';if(c.need?.upgrade&&!s.owned.includes(c.need.upgrade))return 'Нужно: '+upgrades.get(c.need.upgrade).title;if(c.cost>0&&s.cash<c.cost)return `Нужно ${c.cost} £ в кассе`;return '';}
function running(s){const owned=s.owned.map(id=>upgrades.get(id));const gross=55+s.guests*3+owned.reduce((n,u)=>n+(u.revenue||0),0)+(s.flags.menu==='quality'?12:s.flags.menu==='seasonal'?7:0);const upkeep=35+owned.reduce((n,u)=>n+u.maintenance,0);const fatigue=Math.floor(Math.max(0,s.stress-40)/(s.owned.includes('training')?4:2));const debt=s.cash<0?20:0;const supplier=s.owned.includes('roaster')?0:s.trust<30?12:s.trust>=70?-8:0;const reputation=s.rep<40?-12:s.rep>=75?12:0;return {gross:gross+reputation,upkeep:upkeep+supplier,fatigue,debt,net:gross+reputation-upkeep-supplier-fatigue-debt};}
function consequences(e,c,s){const effects={...c.effects,cash:(c.effects.cash||0)-c.cost},notes=[];
const add=(key,n,note)=>{effects[key]=(effects[key]||0)+n;if(note)notes.push(note);};
if(e.id==='supplier-return'&&s.flags.supplier==='broken')add('cash',-30,'После разрыва договора новая доставка потребовала ещё 30 £ на организацию.');
if(e.id==='rush'&&s.flags.review==='promise'){if(c.flags.queue==='split')add('rep',4,'Обещание из ответа на отзыв выполнено: репутация +4.');else add('rep',-6,'Гости вспомнили обещание об отдельной очереди: репутация −6.');}
if(e.id==='team'&&s.stress>=65&&c.flags.team==='bonus')add('stress',12,'При такой усталости премия не заменяет отдых: нагрузка +12.');
if(e.id==='price-rise'){if(s.flags.contract==='fixed')add('cash',45,'Фиксированный договор сберёг 45 £.');if(s.flags.menu==='value'&&c.flags.pricing==='raise')add('guests',-2,'Любители доступного меню чувствительны к повышению: ещё −2 гостя.');if(s.flags.menu==='quality'&&c.flags.pricing==='absorb')add('rep',3,'Приверженность качеству без повышения цены оценили гости: репутация +3.');}
if(e.id==='rain'&&c.flags.rain==='shared'&&s.owned.includes('seating'))add('stress',-5,'Дополнительные места помогли разместить гостей: нагрузка −5.');
if(e.id==='critic'&&c.flags.press==='community'){if(s.flags.identity==='local')add('guests',2,'Приглашённые на открытие соседи привели знакомых: ещё +2 гостя.');if(s.flags.rain==='shelter')add('rep',5,'История укрытия от дождя попала в статью: репутация +5.');}
if(e.id==='critic'&&c.flags.press==='coffee'){if(s.flags.menu==='quality'&&s.owned.includes('espresso'))add('rep',5,'Качество меню подкреплено оборудованием: репутация +5.');if(s.flags.repair==='deferred')add('rep',-8,'Журналистка заметила неисправную машину: репутация −8.');}
if(e.id==='festival'){if(c.flags.festival==='inside'&&s.flags.noise==='paused'&&!s.owned.includes('acoustic'))add('rep',-8,'Вечернее событие нарушило договорённость с соседом: репутация −8.');if(c.flags.festival==='terrace'&&s.flags.repair!=='reliable')add('cash',-80,'Временный ремонт не выдержал фестивальной нагрузки: дополнительные расходы 80 £.');if(s.stress>=65)add('rep',-6,'Перегруженная команда допустила ошибки на фестивале: репутация −6.');if(s.flags.growth==='steady'&&s.owned.includes('training'))add('stress',-6,'Обучение и постепенный рост помогли выдержать фестиваль: нагрузка −6.');}
return {effects,notes};}
function preview(e,c,s){const {effects,notes}=consequences(e,c,s);const next=structuredClone(s);affect(next,effects);Object.assign(next.flags,c.flags);const shift=running(next);affect(next,{cash:shift.net});next.turn++;return {next,effects,notes,shift};}
function apply(game,action,xp,completed){const s=derive(game),log=game.log||[];if(action.type==='buy'){const u=upgrades.get(action.id);const error=canBuy(u,s,xp);if(error)return {ok:false,error};if(game.active)return {ok:false,error:'Заверши или покинь текущий разговор перед покупкой'};return {ok:true,game:{...game,log:[...log,{type:'buy',id:u.id}],active:null}};}
if(action.type==='resolve'){const e=events.get(action.id);if(!e)return {ok:false,error:'Неизвестная история'};const error=access(e,s,xp,completed)||canChoose(e.choices[action.choice],s);if(error)return {ok:false,error};if(!Number.isInteger(action.choice))return {ok:false,error:'Некорректный выбор'};return {ok:true,game:{...game,log:[...log,{type:'resolve',id:e.id,choice:action.choice}],active:null}};}return {ok:false,error:'Неизвестное действие'};}
function derive(game){const s=initial();for(const action of game.log||[]){if(action.type==='buy'){const u=upgrades.get(action.id);if(!u||s.owned.includes(u.id))continue;s.spent+=u.xp;s.cash-=u.cash;s.owned.push(u.id);affect(s,u.effects);}else if(action.type==='resolve'){const e=events.get(action.id),c=e?.choices[action.choice];if(!c||s.turn!==e.index)continue;const p=preview(e,c,s),delta=Object.fromEntries(['cash','rep','trust','stress','guests'].map(key=>[key,p.next[key]-s[key]-(key==='cash'?p.shift.net:0)]));Object.assign(s,p.next);s.history.push({id:e.id,choice:action.choice,title:e.title,result:c.result,notes:p.notes,shift:p.shift,delta});}}return s;}
function valid(raw,xp,completed){let game=fresh();if(!raw||raw.version!==1||!Array.isArray(raw.log))return game;for(const a of raw.log.slice(0,64)){if(!a||!['buy','resolve'].includes(a.type)||typeof a.id!=='string')continue;const r=apply(game,a,xp,completed);if(r.ok)game=r.game;}if(['development','menu','guests','history'].includes(raw.tab))game.tab=raw.tab;const a=raw.active,s=derive(game),e=events.get(a?.id);if(a&&e&&!access(e,s,xp,completed)&&Number.isInteger(a.stage)&&a.stage>=0&&a.stage<=3){const chosen=Number.isInteger(a.choice)&&a.choice>=0&&a.choice<e.choices.length?a.choice:null;if(a.stage===0||chosen!==null&&!canChoose(e.choices[chosen],s)){const task=a.stage===1?e.task:a.stage===2?e.choices[chosen]?.task:null;const nw=task?.answer.split(' ').length||0;game.active={id:e.id,stage:a.stage,choice:chosen,draft:typeof a.draft==='string'?a.draft.slice(0,500):'',words:Array.isArray(a.words)?[...new Set(a.words.filter(n=>Number.isInteger(n)&&n>=0&&n<nw))]:[],answerChoice:Number.isInteger(a.answerChoice)&&a.answerChoice>=0&&a.answerChoice<(task?.options?.length||0)?a.answerChoice:null,passed:a.passed===true&&!!task&&matches(a.draft,task),errors:clamp(Number.isInteger(a.errors)?a.errors:0,0,999),transcript:a.transcript===true};}}return game;}
function norm(s){return String(s??'').toLowerCase().replace(/[’‘]/g,"'").replace(/\bcan't\b/g,'cannot').replace(/\bdon't\b/g,'do not').replace(/\bdoesn't\b/g,'does not').replace(/\bwasn't\b/g,'was not').replace(/\bweren't\b/g,'were not').replace(/\bi'm\b/g,'i am').replace(/\bwe've\b/g,'we have').replace(/\bwe're\b/g,'we are').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ').trim();}
const matches=(answer,task)=>[task.answer,...(task.accept||[])].some(a=>norm(a)===norm(answer));
function ending(s){if(s.turn<D.episodes.length)return null;const path=s.flags.ending;let score=path==='community'?(s.rep+s.guests*2)/2:path==='craft'?s.rep+(s.owned.includes('roaster')?12:0)+(s.flags.repair==='reliable'?8:-10):((100-s.stress)+clamp(s.cash/12,0,60)+s.trust)/2;const strong=score>=75&&s.cash>=0&&s.stress<75;return {path,strong,title:strong?({community:'Место, куда возвращаются',craft:'Свой почерк',sustainable:'Дело, которое выдержало сезон'}[path]):'Сезон закончен. Работа продолжается.',text:strong?'Выбранное направление подкреплено решениями: у кафе есть запас для следующего сезона.':'Направление выбрано, но остались слабые места. Посмотри финансы, нагрузку и историю обещаний: красивые слова не отменяют последствий.'};}
window.CafeEngine={fresh,initial,derive,apply,valid,access,canBuy,canChoose,preview,details,running,ending,matches,events,upgrades,data:D};
})();
