window.installLearning=api=>{
 const {app,esc,icon,save,state:current,course:C,image,speak,stopSpeech,matches,today,openModal,modal,toast}=api,K=window.LearningCore;
 const s=()=>current(),lesson=id=>C.lessons.find(l=>l.id===id),opened=()=>K.articles.filter(a=>K.unlocked(a,s().completed));
 const speeds=[.7,.85,1,1.15,1.3],speed=()=>`<label class="audio-speed"><span class="sr-only">Скорость воспроизведения</span><select data-learning-speed aria-label="Скорость воспроизведения">${speeds.map(v=>`<option value="${v}" ${v===s().settings.speed?'selected':''}>${String(v).replace('.',',')}×</option>`).join('')}</select></label>`;
 const heading=(title,back)=>`<div class="learning-heading"><a class="icon-btn" href="#${back}" aria-label="Назад">${icon('back')}</a><h1>${esc(title)}</h1></div>`;
 function bindAudio(){app.querySelectorAll('[data-learning-speed]').forEach(el=>el.onchange=()=>{s().settings.speed=+el.value;stopSpeech();save();});}
 function practiceHome(){
  const count=Object.keys(s().practiceDone).length,active=s().drill,has=opened().length>0;
  const tile=(route,title,sub,i)=>`<a class="practice-mode ${has?'':'mode-locked'}" href="#${route}" ${!has?'aria-disabled="true"':''}><span class="mode-symbol">${icon(i)}</span><h2>${title}</h2><p>${sub}</p>${icon(has?'arrow':'lock')}</a>`;
  return `<div class="view learning-home"><div class="eyebrow">В другой ситуации</div><h1>Практика</h1><p class="learning-subtitle">Знакомые правила. Совсем другие истории.</p><section class="practice-feature"><img src="assets/cafe.webp" alt="Уютное кафе вечером"><div class="feature-copy"><span class="eyebrow">${active?'Твоя тренировка':'Небольшая разминка'}</span><h2>${active?'Продолжим с места остановки':has?'Освежим знакомое':'Начнём с эпизода'}</h2><p>${active?`Задание ${active.index+1} из ${active.ids.length}`:has?'5 заданий · по пройденным темам':'После урока здесь откроются упражнения'}</p><a class="primary" href="#${has?'drill/mix':'home'}">${active?'Продолжить':has?'Начать':'К эпизодам'} ${icon('arrow')}</a></div></section><div class="practice-modes">${tile('drill/listen','На слух','Узнай смысл, а не отдельные слова','headphones')}${tile('speaking','Разговорная речь','Диалог по знакомой теме','volume')}${tile('drill/fix','Исправь фразу','Найди и исправь ошибку','edit')}${tile('drill/rewrite','Скажи иначе','Передай мысль новой конструкцией','repeat')}</div><a class="archive-entry" href="#practice-archive"><span class="mode-symbol">${icon('episodes')}</span><div><h2>Практика по эпизодам</h2><p>${count} из ${C.lessons.length} завершено · по модулям</p></div>${icon('chevron')}</a><a class="collection-shortcut text-link" href="#collection">Моя коллекция ${icon('album')}</a></div>`;
 }
 let archiveFilter='pending',archiveQuery='';
 function archiveResults(){const q=archiveQuery.toLowerCase().trim();return C.modules.map(m=>{const accessible=m.lessons.filter(id=>s().completed[id]),ids=accessible.filter(id=>{const l=lesson(id),done=!!s().practiceDone[id];return (archiveFilter==='all'||archiveFilter==='done'&&done||archiveFilter==='pending'&&(!done||(s().practiceActive?.lesson===id&&s().practiceActive.replay)))&&(!q||(`${l.ru} ${l.title} ${window.TRANSFER_PRACTICE.lessons[id].title} ${m.title} ${l.number}`).toLowerCase().includes(q));});if(!ids.length)return '';return `<details class="practice-module" ${q||C.modules.find(mm=>mm.lessons.some(id=>s().completed[id]&&(archiveFilter!=='pending'||!s().practiceDone[id]||(s().practiceActive?.lesson===id&&s().practiceActive.replay))))?.id===m.id?'open':''}><summary><div><span class="eyebrow">Модуль ${m.number} · ${m.band}</span><h2>${esc(m.title)}</h2><p>${accessible.filter(id=>s().practiceDone[id]).length} из ${accessible.length} доступных завершено</p></div><span class="module-count">${ids.length}</span>${icon('chevron')}</summary><div class="archive-rows">${ids.map(id=>{const l=lesson(id),done=!!s().practiceDone[id],active=s().practiceActive?.lesson===id&&(!done||s().practiceActive.replay);return `<a class="archive-row" href="#${done&&!active?'practice-complete':'transfer'}/${id}"><img src="${image(l)}" alt=""><div><span class="eyebrow">Эпизод ${l.number}</span><h3>${esc(window.TRANSFER_PRACTICE.lessons[id].title)}</h3><p>${active?'Продолжить · '+(s().practiceActive.index+1)+'/4':done?'Завершено · Повторить':'4 задания · игрушка в коллекцию'}</p></div>${icon(done?'check':'arrow')}</a>`;}).join('')}</div></details>`;}).join('')||`<div class="learning-empty">${icon('book')}<h2>${q?'Ничего не найдено':archiveFilter==='pending'&&opened().length?'Всё закреплено':'Здесь пока пусто'}</h2><p>${q?'Попробуй другое слово или фильтр.':'Наборы открываются после завершения эпизодов.'}</p>${archiveFilter==='pending'&&opened().length?'<button class="secondary" data-show-all>Все наборы</button>':'<a class="secondary" href="#home">К эпизодам</a>'}</div>`;}
 function archive(){app.innerHTML=`<div class="view learning-home">${heading('По эпизодам','practice')}<p class="learning-subtitle">Четыре новых задания — одна игрушка на полке.</p><label class="learning-search">${icon('book')}<input id="archive-search" type="search" placeholder="Найти тему или эпизод" aria-label="Поиск практики" value="${esc(archiveQuery)}"></label><div class="learning-tabs">${[['pending','Закрепить'],['done','Пройдено'],['all','Все']].map(([id,name])=>`<button data-archive-filter="${id}" class="${id===archiveFilter?'selected':''}" aria-pressed="${id===archiveFilter}">${name}</button>`).join('')}</div><div id="archive-results">${archiveResults()}</div></div>`;const update=()=>{app.querySelector('#archive-results').innerHTML=archiveResults();const all=app.querySelector('[data-show-all]');if(all)all.onclick=()=>{archiveFilter='all';archive();};};app.querySelector('#archive-search').oninput=e=>{archiveQuery=e.target.value;update();};app.querySelectorAll('[data-archive-filter]').forEach(b=>b.onclick=()=>{archiveFilter=b.dataset.archiveFilter;app.querySelectorAll('[data-archive-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});update();});update();}
 let ruleQuery='',ruleFilter='all';
 function ruleRows(){const q=ruleQuery.trim().toLowerCase(),list=K.articles.filter(a=>(ruleFilter==='all'||a.category===ruleFilter)&&(!q||(`${a.title} ${a.topicKey} ${a.lessons.join(' ')}`).toLowerCase().includes(q))),avail=list.filter(a=>K.unlocked(a,s().completed)),locked=list.filter(a=>!K.unlocked(a,s().completed));return `${avail.length?`<div class="rule-list">${avail.map(a=>`<a class="rule-row" href="#rule/${a.id}"><span class="mode-symbol">${icon(a.category==='speech'?'volume':'book')}</span><div><span class="eyebrow">${a.category==='speech'?'Разговор':'Грамматика'}</span><h2>${esc(a.title)}</h2><p>${a.lessons.filter(id=>s().completed[id]).length>1?'Знакомо по нескольким эпизодам':'Из эпизода '+lesson(a.lessons.find(id=>s().completed[id])).number}</p></div>${icon('chevron')}</a>`).join('')}</div>`:q?'':`<div class="learning-empty"><h2>Справочник растёт вместе с тобой</h2><p>Заверши эпизод — его правило появится здесь.</p><a href="#home" class="secondary">К эпизодам</a></div>`}${locked.length?`<details class="future-rules" ${q?'open':''}><summary>Впереди · ${locked.length} тем ${icon('lock')}</summary><div class="rule-list">${locked.map(a=>`<div class="rule-row locked-rule"><span class="mode-symbol">${icon('lock')}</span><div><h2>${esc(a.title)}</h2><p>После эпизода ${lesson(a.lessons[0]).number} · ${lesson(a.lessons[0]).band}</p></div></div>`).join('')}</div></details>`:''}${!list.length?'<div class="learning-empty"><h2>Ничего не найдено</h2><p>Попробуй другое название или категорию.</p></div>':''}`;}
 function reference(){const avail=opened(),featured=avail.slice().sort((a,b)=>Math.max(...b.lessons.filter(id=>s().completed[id]).map(id=>Date.parse(s().completed[id].at)||0))-Math.max(...a.lessons.filter(id=>s().completed[id]).map(id=>Date.parse(s().completed[id].at)||0)))[0];app.innerHTML=`<div class="view learning-home reference-home"><div class="eyebrow">Всегда под рукой</div><h1>Правила</h1><p class="learning-subtitle">${avail.length} из ${K.articles.length} тем открыто. Понятно, подробно, с примерами.</p>${featured?`<a class="reference-feature" href="#rule/${featured.id}"><img src="assets/rules-desk.webp" alt="Блокнот и тёплый свет настольной лампы"><div><span class="eyebrow">Недавно изучено</span><h2>${esc(featured.title)}</h2><span class="text-link">Разобраться ещё раз ${icon('arrow')}</span></div></a>`:''}<label class="learning-search">${icon('book')}<input id="rule-search" type="search" placeholder="Найти правило" aria-label="Поиск правил" value="${esc(ruleQuery)}"></label><div class="learning-tabs">${[['all','Все'],['grammar','Грамматика'],['speech','Разговор']].map(([id,name])=>`<button data-rule-filter="${id}" class="${id===ruleFilter?'selected':''}" aria-pressed="${id===ruleFilter}">${name}</button>`).join('')}</div><div id="rule-results">${ruleRows()}</div></div>`;app.querySelector('#rule-search').oninput=e=>{ruleQuery=e.target.value;app.querySelector('#rule-results').innerHTML=ruleRows();};app.querySelectorAll('[data-rule-filter]').forEach(b=>b.onclick=()=>{ruleFilter=b.dataset.ruleFilter;app.querySelectorAll('[data-rule-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});app.querySelector('#rule-results').innerHTML=ruleRows();});}
 function article(id){const a=K.rules.get(id);if(!a){location.hash='rules';return;}if(!K.unlocked(a,s().completed)){app.innerHTML=`<div class="view learning-home">${heading('Правило закрыто','rules')}<div class="learning-empty">${icon('lock')}<h2>${esc(a.title)}</h2><p>Откроется после завершения одного из эпизодов этой темы.</p>${a.lessons.map(id=>`<a class="secondary" href="#lesson/${id}">Эпизод ${lesson(id).number} · ${esc(lesson(id).ru)}</a>`).join('')}</div></div>`;return;}
  const done=a.lessons.filter(id=>s().completed[id]),l=lesson(done[0]),notes=[...new Set(done.slice(1).map(id=>lesson(id).guided.cards[0].note).filter(n=>n&&n!==l.guided.cards[0].note))];
  app.innerHTML=`<article class="view rule-article"><div class="learning-heading"><a class="icon-btn" href="#rules" aria-label="Назад ко всем правилам">${icon('back')}</a><span class="learning-back-label">Все правила</span></div><div class="eyebrow">${a.category==='speech'?'Разговорная речь':'Грамматика'} · ${l.band}</div><h1>${esc(a.title)}</h1><p class="rule-intro">${esc(a.intro)}</p><section class="rule-formula"><span class="eyebrow">Опорная схема</span><p lang="en">${esc(l.guided.cards[0].rule)}</p></section><section class="rule-section"><h2>Как это работает</h2>${a.details.map((p,i)=>`<div class="rule-paragraph"><span class="rule-number">${i+1}</span><p>${esc(p)}</p></div>`).join('')}</section><section class="rule-section"><div class="rule-section-title"><h2>На примерах</h2>${speed()}</div><div class="rule-examples">${a.examples.map(([en,ru],i)=>`<div class="rule-example"><div><p lang="en">${esc(en)}</p><span>${esc(ru)}</span></div><button class="icon-btn" data-example="${i}" aria-label="Послушать пример ${i+1}">${icon('volume')}</button></div>`).join('')}</div></section><section class="rule-section rule-error"><span class="eyebrow">Частая ошибка</span><p class="incorrect" lang="en">${esc(a.error.bad)}</p><p class="correct" lang="en">${esc(a.error.good)}</p><p>${esc(a.error.why)}</p></section><section class="rule-section"><h2>Как это звучит в разговоре</h2><p>${esc(a.speech)}</p></section>${notes.length?`<section class="rule-section"><h2>Из следующих пройденных эпизодов</h2>${notes.map(n=>`<p>${esc(n)}</p>`).join('')}</section>`:''}<a class="primary" href="#drill/${id}">Попробовать на новых примерах ${icon('arrow')}</a><details class="rule-sources"><summary>Уроки и источники ${icon('book')}</summary><div>${done.map(id=>`<a href="#lesson/${id}">Повторить эпизод ${lesson(id).number}: ${esc(lesson(id).ru)}</a>`).join('')}<a href="${esc(a.source)}" target="_blank" rel="noopener noreferrer">${a.source.includes('cambridge')?'Cambridge Dictionary · English Grammar':'British Council · LearnEnglish'} ↗</a>${a.sources?.map(url=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Дополнительный материал ↗</a>`).join('')||''}<a href="${esc(l.guided.source||l.url)}" target="_blank" rel="noopener noreferrer">Материал эпизода ↗</a></div></details></article>`;
  app.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>speak(a.examples[+b.dataset.example][0]));bindAudio();
 }
 function startDrill(id='mix'){const topic=K.rules.has(id)?id:null,mode=topic?'mix':['mix','listen','fix','rewrite'].includes(id)?id:null;if(!mode){location.hash='practice';return;}if(!K.available(s().completed,mode,topic).length){app.innerHTML=`<div class="view learning-home">${heading('Практика','practice')}<div class="learning-empty">${icon('lock')}<h2>Эта тема ещё впереди</h2><p>Сначала заверши эпизод, чтобы открыть его упражнения.</p><a href="#home" class="primary">К эпизодам</a></div></div>`;return;}
  if(s().drill){const a=s().drill;if((!topic&&id==='mix')||(a.mode===mode&&a.topic===topic)){renderDrill();return;}app.innerHTML=`<div class="view learning-home">${heading('Новая тренировка','practice')}<section class="learning-empty"><h2>Есть незаконченная попытка</h2><p>Ты остановился на задании ${a.index+1} из ${a.ids.length}. Можно продолжить её или начать другой режим.</p><button class="primary" id="resume-drill">Продолжить попытку</button><button class="secondary" id="replace-drill">Начать другую</button></section></div>`;app.querySelector('#resume-drill').onclick=()=>{const route=a.topic||a.mode;if(id!==route)location.hash='drill/'+route;else renderDrill();};app.querySelector('#replace-drill').onclick=()=>{openModal('Начать другую тренировку?',`<p>Черновик текущей попытки будет заменён. Уже выполненные упражнения останутся в истории.</p><button class="primary" id="confirm-drill">Начать другую</button>`);modal.querySelector('#confirm-drill').onclick=()=>{modal.close();newDrill(mode,topic);};};return;}
  newDrill(mode,topic);
 }
 function newDrill(mode,topic){s().drill={ids:K.choose(s().completed,s().drillHistory,mode,topic),index:0,mode,topic,draft:'',choice:null,passed:false,errors:0,textMode:false,started:new Date().toISOString()};save();renderDrill();}
 function renderDrill(){const a=s().drill;if(!a){location.hash='practice';return;}const t=K.tasks.get(a.ids[a.index]),r=K.rules.get(t.rule),label={listen:'На слух',fix:'Исправь фразу',rewrite:'Скажи иначе'}[t.type];app.innerHTML=`<div class="view drill-view"><div class="drill-top"><a class="icon-btn" href="#practice" aria-label="Выйти и сохранить попытку">${icon('close')}</a><span>Задание ${a.index+1}/${a.ids.length}</span><a class="icon-btn" href="#rule/${r.id}" aria-label="Открыть правило">${icon('book')}</a></div><div class="progress-track" role="progressbar" aria-label="Прогресс тренировки" aria-valuemin="0" aria-valuemax="${a.ids.length}" aria-valuenow="${a.index+(a.passed?1:0)}"><span style="width:${(a.index+(a.passed?1:0))/a.ids.length*100}%"></span></div><div class="eyebrow">${label}</div><h1>${esc(r.title)}</h1><p class="drill-prompt">${esc(t.prompt)}</p>${t.audio?`<div class="drill-audio"><button id="drill-play" class="secondary">${icon('volume')} Послушать</button>${speed()}</div><button id="drill-text" class="text-link">${a.textMode?'Скрыть текст':'Показать текст'}</button>${a.textMode?`<p class="drill-quote" lang="en">${esc(t.audio)}</p>`:''}`:`<p class="drill-quote" lang="en">${esc(t.display)}</p>`}${t.options?`<div class="options">${t.options.map((o,i)=>`<button data-drill-choice="${i}" class="option ${a.choice===i?'selected':''}" aria-pressed="${a.choice===i}" ${a.passed?'disabled':''}>${esc(o)}</button>`).join('')}</div>`:`<label class="answer-label" for="drill-answer">Твоя версия</label><textarea class="response" id="drill-answer" maxlength="1200" rows="3" lang="en" spellcheck="false" autocapitalize="sentences" ${a.passed?'readonly':''}>${esc(a.draft)}</textarea>`}<div id="drill-feedback" role="status" aria-live="polite">${a.passed?goodFeedback(t):''}</div><button class="primary" id="drill-check">${a.passed?(a.index===a.ids.length-1?'Завершить':'Дальше'):'Проверить'} ${icon('arrow')}</button></div>`;
  const check=app.querySelector('#drill-check'),enable=()=>check.disabled=!a.passed&&(t.options?a.choice===null:!a.draft.trim());enable();
  const input=app.querySelector('#drill-answer');if(input){input.oninput=()=>{a.draft=input.value;save();enable();};input.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!check.disabled)check.click();};}
  app.querySelectorAll('[data-drill-choice]').forEach(b=>b.onclick=()=>{if(a.passed)return;a.choice=+b.dataset.drillChoice;save();app.querySelectorAll('[data-drill-choice]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});enable();});
  const play=app.querySelector('#drill-play');if(play)play.onclick=()=>speak(t.audio);const text=app.querySelector('#drill-text');if(text)text.onclick=()=>{a.textMode=!a.textMode;save();renderDrill();};bindAudio();
  check.onclick=()=>{if(a.passed){stopSpeech();if(a.index===a.ids.length-1){s().drillLast={ids:a.ids.slice(),errors:a.errors,at:new Date().toISOString()};s().drill=null;save();location.hash='drill-complete';return;}Object.assign(a,{index:a.index+1,draft:'',choice:null,passed:false,textMode:false});save();renderDrill();window.scrollTo({top:0,behavior:'instant'});return;}
   if(K.grade(t,a,matches)){a.passed=true;const old=s().drillHistory[t.id];s().drillHistory[t.id]={count:Math.min(100000,(old?.count||0)+1),at:new Date().toISOString()};s().activity[today()]=(s().activity[today()]||0)+1;save();renderDrill();}else{a.errors=Math.min(999,a.errors+1);save();app.querySelector('#drill-feedback').innerHTML=`<div class="feedback bad"><strong>Попробуй ещё раз</strong><p>${t.options?'Переслушай реплику и сравни смысл вариантов.':'Проверь форму и порядок слов. Смысл и остальные слова нужно сохранить.'}</p><details><summary>Разобрать ответ</summary><p lang="en">${esc(t.options?t.audio:t.answer)}</p><p>${esc(t.why)}</p></details></div>`;}}
 }
 function goodFeedback(t){return `<div class="feedback"><strong>Верно</strong><p>${esc(t.options?t.why:t.answer)}</p>${!t.options?`<details><summary>Почему так</summary><p>${esc(t.why)}</p></details>`:''}</div>`;}
 function recap(){const a=s().drillLast;if(!a){location.hash='practice';return;}const topics=[...new Set(a.ids.map(id=>K.tasks.get(id).rule))];app.innerHTML=`<div class="view learning-home drill-recap">${heading('Тренировка','practice')}<div class="recap-orbit">✓</div><div class="eyebrow">Завершено</div><h1>Знакомое стало увереннее.</h1><p class="learning-subtitle">${a.ids.length} заданий · ${a.errors} ${a.errors===1?'ошибка':a.errors>=2&&a.errors<=4?'ошибки':'ошибок'} в попытке</p><div class="rule-list">${topics.map(id=>`<a class="rule-row" href="#rule/${id}"><div><h2>${esc(K.rules.get(id).title)}</h2><p>Вернуться к объяснению</p></div>${icon('book')}</a>`).join('')}</div><a class="primary" href="#drill/mix">Ещё одна разминка ${icon('repeat')}</a><a class="secondary" href="#practice">К практике</a></div>`;}
 function writing(){const entries=Object.entries(s().journal).filter(([id,text])=>lesson(id)&&text.trim());app.innerHTML=`<div class="view learning-home">${heading('Мои записи','settings')}<p class="learning-subtitle">Истории, написанные после уроков. Сохраняются без автоматической оценки.</p>${entries.map(([id,text])=>`<section class="writing-entry"><span class="eyebrow">Эпизод ${lesson(id).number}</span><h2>${esc(lesson(id).ru)}</h2><label class="sr-only" for="writing-${id}">История эпизода ${lesson(id).number}</label><textarea class="response" id="writing-${id}" data-writing="${id}" rows="4" maxlength="3000" lang="en">${esc(text)}</textarea><span class="source-note" data-writing-status="${id}"></span></section>`).join('')||'<div class="learning-empty"><h2>Пока нет записей</h2><p>Своя история в конце урока появится здесь.</p></div>'}</div>`;app.querySelectorAll('[data-writing]').forEach(el=>el.oninput=()=>{s().journal[el.dataset.writing]=el.value;save();app.querySelector(`[data-writing-status="${el.dataset.writing}"]`).textContent='Сохранено';});}
 return {practiceHome,archive,reference,article,startDrill,recap,writing};
};
