/* Collection identity is stable: ordinal = variation * 12 + species.
   Unlocks are derived from validated lesson/practice records, never a second ledger. */
(()=>{
'use strict';
const species=[['bear','Мишки','Мишка'],['cat','Кошки','Кошка'],['rabbit','Зайки','Зайка'],['dog','Собаки','Щенок'],['fox','Лисы','Лисёнок'],['panda','Панды','Панда'],['otter','Выдры','Выдра'],['penguin','Пингвины','Пингвин'],['elephant','Слоны','Слонёнок'],['owl','Совы','Совёнок'],['raccoon','Еноты','Енот'],['deer','Олени','Оленёнок']].map(([id,title,name])=>({id,title,name}));
const variations=[['Тёплая встреча','Мягкий зелёный шарф и первый уютный вечер.'],['Осенний уют','Терракотовый кардиган с маленькими пуговицами.'],['После дождя','Жёлтый плащ для прогулок в любую погоду.'],['Морской воздух','Синий полосатый свитер и настроение выходного дня.'],['Лавандовый день','Сиреневый комбинезон с аккуратной вышивкой.'],['Особый вечер','Бархатный бордовый жилет и праздничный бант.'],['Тихое утро','Светлый вязаный свитер и немного спокойствия.']];
const toys=Array.from({length:84},(_,i)=>({id:species[i%12].id+'-'+(Math.floor(i/12)+1),ordinal:i,species:species[i%12].id,variation:Math.floor(i/12),name:species[i%12].name,title:variations[Math.floor(i/12)][0],description:variations[Math.floor(i/12)][1],lesson:window.COURSE.lessons[i]?.id||null,bonus:i>=82}));
function unlocked(toy,s){if(toy.ordinal<82)return !!s.practiceDone?.[toy.lesson];const courseDone=window.COURSE.lessons.every(l=>!!s.completed?.[l.id]);return toy.ordinal===82?courseDone:courseDone&&window.COURSE.lessons.every(l=>!!s.practiceDone?.[l.id]);}
const count=s=>toys.filter(t=>unlocked(t,s)).length;
function badges(s){return [{id:'plush-first',title:'Первый сосед',desc:'Получи первую плюшевую игрушку',icon:'album',earned:count(s)>0},{id:'plush-42',title:'Большая компания',desc:'Собери 42 игрушки',icon:'star',earned:count(s)>=42},...species.map(a=>({id:'plush-'+a.id,title:a.title+' · полный набор',desc:'Собери все 7 вариаций',icon:'award',earned:toys.filter(t=>t.species===a.id).every(t=>unlocked(t,s))})),{id:'plush-all',title:'Все дома',desc:'Собери все 84 игрушки',icon:'album',earned:count(s)===84}];}
function install(api){const {esc,icon,state,app,modal,openModal}=api;
 function art(t,locked=false){return `<span class="plush-art ${locked?'plush-shadow':''}" style="--plush-image:url('assets/plush/${t.species}.png');--plush-x:${(t.variation%4)*100/3}%;--plush-y:${t.variation<4?0:100}%" aria-hidden="true"></span>`;}
 function condition(t){if(t.ordinal===82)return 'Заверши все 82 эпизода.';if(t.ordinal===83)return 'Собери остальные 83 игрушки: заверши все эпизоды и их практику.';const l=window.COURSE.lessons.find(l=>l.id===t.lesson);return `Заверши практику эпизода ${l.number} «${l.ru}».`;}
 function collection(){const s=state(),n=count(s);return `<div class="view profile-subpage collection-view plush-view"><div class="subpage-heading"><a class="icon-btn" href="#profile" aria-label="Назад в профиль">${icon('back')}</a><h1>Коллекция</h1></div><div class="plush-summary"><span><strong>${n}</strong> / 84 <span class="muted">дома</span></span><span>12 животных · 7 вариаций</span></div><div class="plush-progress" role="progressbar" aria-label="Коллекция" aria-valuenow="${n}" aria-valuemin="0" aria-valuemax="84"><span style="width:${n/84*100}%"></span></div><div class="collection-grid plush-cabinet">${species.map(a=>{const set=toys.filter(t=>t.species===a.id),owned=set.filter(t=>unlocked(t,s)).length;return `<section class="plush-family ${owned===7?'plush-family-complete':''}" aria-label="${a.title}: ${owned} из 7"><div class="plush-family-head"><h2>${a.title}</h2><span>${owned===7?icon('check'):''}${owned}<span class="muted"> / 7</span></span></div>${[set.slice(0,4),set.slice(4)].map((row,j)=>`<div class="plush-shelf ${j?'plush-shelf-three':''}">${row.map(t=>{const yes=unlocked(t,s);return `<button class="plush-slot ${yes?'owned':'locked'}" data-plush="${t.id}" aria-label="${t.name}, ${t.title}, ${yes?'в коллекции':'ещё закрыто'}">${art(t,!yes)}<span class="plush-slot-caption">${yes?esc(t.title):'·'}</span>${t.bonus?'<span class="plush-bonus" aria-label="Бонусная игрушка">✦</span>':''}</button>`;}).join('')}</div>`).join('')}</section>`;}).join('')}</div><details class="plush-about"><summary>Как пополнять полки</summary><p>За каждую завершённую практику — новая игрушка. Животные чередуются: сначала первые вариации всех 12 видов, затем вторые и так далее. Две последние игрушки — за завершение курса и всей коллекции. Повторение практики не меняет награды.</p></details></div>`;}
 function bindCollection(){app.querySelectorAll('[data-plush]').forEach(b=>b.onclick=()=>{const t=toys.find(t=>t.id===b.dataset.plush);if(!t)return;const yes=unlocked(t,state()),l=window.COURSE.lessons.find(l=>l.id===t.lesson);openModal(t.name+' · '+t.title,`<div class="plush-detail ${yes?'':'is-locked'}">${art(t,!yes)}</div><p class="plush-description">${yes?esc(t.description):esc(condition(t))}</p><p class="plush-provenance">${yes?(t.bonus?'Бонус коллекции':`За практику эпизода ${l.number} «${esc(l.ru)}»`):'Место на полке уже ждёт своего хозяина'}</p>${!yes&&l?`<a class="primary" href="#${state().completed[l.id]?'transfer':'lesson'}/${l.id}">${state().completed[l.id]?'К практике':'К эпизоду'} ${icon('arrow')}</a>`:''}`);modal.querySelector('a')?.addEventListener('click',()=>modal.close());});}
 function reward(id){const t=toys.find(t=>t.lesson===id);return `<div class="plush-reward">${art(t)}<h2>${t.name} · ${t.title}</h2><p>${esc(t.description)}</p></div>`;}
 return {collection,bindCollection,reward};
}
window.PLUSH_COLLECTION=Object.freeze({species,toys,unlocked,count,badges,install});
})();
