/* Collection identity is stable: ordinal = variation * 12 + species.
   Unlocks are derived from validated lesson/practice records, never a second ledger. */
(()=>{
'use strict';
const species=[['bear','Мишки','Мишка'],['cat','Кошки','Кошка'],['rabbit','Зайки','Зайка'],['dog','Собаки','Щенок'],['fox','Лисы','Лисёнок'],['panda','Панды','Панда'],['otter','Выдры','Выдра'],['penguin','Пингвины','Пингвин'],['elephant','Слоны','Слонёнок'],['owl','Совы','Совёнок'],['raccoon','Еноты','Енот'],['deer','Олени','Оленёнок']].map(([id,title,name])=>({id,title,name}));
const variations=[['Тёплая встреча','Мягкий зелёный шарф и первый уютный вечер.'],['Осенний уют','Терракотовый кардиган с маленькими пуговицами.'],['После дождя','Жёлтый плащ для прогулок в любую погоду.'],['Морской воздух','Синий полосатый свитер и настроение выходного дня.'],['Лавандовый день','Сиреневый комбинезон с аккуратной вышивкой.'],['Особый вечер','Бархатный бордовый жилет и праздничный бант.'],['Тихое утро','Светлый вязаный свитер и немного спокойствия.']];
const toys=Array.from({length:84},(_,i)=>({id:species[i%12].id+'-'+(Math.floor(i/12)+1),ordinal:i,species:species[i%12].id,variation:Math.floor(i/12),name:species[i%12].name,title:variations[Math.floor(i/12)][0],description:variations[Math.floor(i/12)][1],lesson:window.COURSE.lessons[i]?.id||null,bonus:i>=82}));
function assignments(raw,done){
 const ids=window.COURSE.lessons.map(l=>l.id),result={},used=new Set();
 // Retain awarded identities from the previous deterministic collection.
 for(const id of ids){const value=raw?.[id];if(typeof value==='string'&&toys.slice(0,82).some(t=>t.id===value)&&!used.has(value)){result[id]=value;used.add(value);}}
 for(const id of ids)if(done?.[id]&&!result[id]){const old=toys.find(t=>t.lesson===id);if(!used.has(old.id)){result[id]=old.id;used.add(old.id);}}
 const pool=toys.slice(0,82).filter(t=>!used.has(t.id));
 function random(n){const x=new Uint32Array(1);let v;const limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(x);v=x[0];}while(v>=limit);return v%n;}
 let previous=null;
 for(const id of ids){if(result[id]){previous=toys.find(t=>t.id===result[id]);continue;}let candidates=pool.filter(t=>!previous||(t.species!==previous.species&&t.variation!==previous.variation));if(!candidates.length)candidates=pool;const t=candidates[random(candidates.length)];result[id]=t.id;pool.splice(pool.indexOf(t),1);previous=t;}
 return result;
}
function lessonForToy(toy,s){return window.COURSE.lessons.find(l=>(s.plushAssignments?.[l.id]||toys.find(t=>t.lesson===l.id)?.id)===toy.id);}
function unlocked(toy,s){if(toy.ordinal<82)return !!s.practiceDone?.[lessonForToy(toy,s)?.id];const courseDone=window.COURSE.lessons.every(l=>!!s.completed?.[l.id]);return toy.ordinal===82?courseDone:courseDone&&window.COURSE.lessons.every(l=>!!s.practiceDone?.[l.id]);}
const count=s=>toys.filter(t=>unlocked(t,s)).length;
function badges(s){return [{id:'plush-first',title:'Первый сосед',desc:'Получи первую плюшевую игрушку',icon:'album',earned:count(s)>0},{id:'plush-42',title:'Большая компания',desc:'Собери 42 игрушки',icon:'star',earned:count(s)>=42},...species.map(a=>({id:'plush-'+a.id,title:a.title+' · полный набор',desc:'Собери все 7 вариаций',icon:'award',earned:toys.filter(t=>t.species===a.id).every(t=>unlocked(t,s))})),{id:'plush-all',title:'Все дома',desc:'Собери все 84 игрушки',icon:'album',earned:count(s)===84}];}
function install(api){const {esc,icon,state,app,modal,openModal}=api;
 function art(t,locked=false){return `<span class="plush-art ${locked?'plush-shadow':''}" style="--plush-image:url('assets/plush/${t.species}.png');--plush-x:${(t.variation%4)*100/3}%;--plush-y:${t.variation<4?0:100}%" aria-hidden="true"></span>`;}
 function condition(t){if(t.ordinal===82)return 'Заверши все 82 эпизода.';if(t.ordinal===83)return 'Собери остальные 83 игрушки: заверши все эпизоды и их практику.';return 'Заверши новую практику: следующая игрушка станет сюрпризом.';}
 function collection(){const s=state(),n=count(s);return `<div class="view profile-subpage collection-view plush-view"><div class="subpage-heading"><a class="icon-btn" href="#profile" aria-label="Назад в профиль">${icon('back')}</a><h1>Коллекция</h1></div><div class="plush-summary"><span><strong>${n}</strong> / 84 <span class="muted">дома</span></span><span>12 животных · 7 вариаций</span></div><div class="plush-progress" role="progressbar" aria-label="Коллекция" aria-valuenow="${n}" aria-valuemin="0" aria-valuemax="84"><span style="width:${n/84*100}%"></span></div><div class="collection-grid plush-cabinet">${species.map(a=>{const set=toys.filter(t=>t.species===a.id),owned=set.filter(t=>unlocked(t,s)).length;return `<section class="plush-family ${owned===7?'plush-family-complete':''}" aria-label="${a.title}: ${owned} из 7"><div class="plush-family-head"><h2>${a.title}</h2><span>${owned===7?icon('check'):''}${owned}<span class="muted"> / 7</span></span></div>${[set.slice(0,4),set.slice(4)].map((row,j)=>`<div class="plush-shelf ${j?'plush-shelf-three':''}">${row.map(t=>{const yes=unlocked(t,s);return `<button class="plush-slot ${yes?'owned':'locked'}" data-plush="${t.id}" aria-label="${t.name}, ${t.title}, ${yes?'в коллекции':'ещё закрыто'}">${art(t,!yes)}<span class="plush-slot-caption">${yes?esc(t.title):'·'}</span>${t.bonus?'<span class="plush-bonus" aria-label="Бонусная игрушка">✦</span>':''}</button>`;}).join('')}</div>`).join('')}</section>`;}).join('')}</div><details class="plush-about"><summary>Как пополнять полки</summary><p>За каждую завершённую практику — новая игрушка. Животные и наряды перемешаны. Каждая новая практика открывает уникальную игрушку без повторов. Две последние игрушки — за завершение курса и всей коллекции. Повторение практики не меняет награды.</p></details></div>`;}
 function bindCollection(){app.querySelectorAll('[data-plush]').forEach(b=>b.onclick=()=>{const t=toys.find(t=>t.id===b.dataset.plush);if(!t)return;const yes=unlocked(t,state()),l=lessonForToy(t,state());openModal(t.name+' · '+t.title,`<div class="plush-detail ${yes?'':'is-locked'}">${art(t,!yes)}</div><p class="plush-description">${yes?esc(t.description):esc(condition(t))}</p><p class="plush-provenance">${yes?(t.bonus?'Бонус коллекции':`За практику эпизода ${l.number} «${esc(l.ru)}»`):'Место на полке уже ждёт своего хозяина'}</p>`);modal.querySelector('a')?.addEventListener('click',()=>modal.close());});}
 function reward(id){const t=toys.find(t=>t.id===state().plushAssignments?.[id])||toys.find(t=>t.lesson===id);return `<div class="plush-reward">${art(t)}<h2>${t.name} · ${t.title}</h2><p>${esc(t.description)}</p></div>`;}
 function preview(){const s=state(),owned=toys.filter(t=>unlocked(t,s)).sort((a,b)=>{const la=lessonForToy(a,s),lb=lessonForToy(b,s);return String(s.practiceDone[la?.id]?.at||'9999').localeCompare(String(s.practiceDone[lb?.id]?.at||'9999'));}).slice(-3);return `<div class="profile-shelf plush-shelf plush-shelf-three"><img class="shelf-environment" src="assets/profile-shelf.webp" alt="" loading="lazy">${Array.from({length:3},(_,i)=>owned[i]?`<button class="plush-slot owned" data-plush="${owned[i].id}" aria-label="${esc(owned[i].name+' · '+owned[i].title)}">${art(owned[i])}</button>`:`<span class="shelf-empty" aria-label="Место для новой игрушки">${icon('star')}</span>`).join('')}</div><p class="shelf-count">${count(s)} ${count(s)%10===1&&count(s)%100!==11?'игрушка':count(s)%10>=2&&count(s)%10<=4&&(count(s)%100<12||count(s)%100>14)?'игрушки':'игрушек'} из 84</p>`;}
 return {collection,bindCollection,reward,preview};
}
window.PLUSH_COLLECTION=Object.freeze({species,toys,unlocked,count,badges,assignments,install});
})();
