// Independent transfer sessions: lesson drafts and lesson XP are never overwritten.
window.installTransferPractice=api=>{
 const {app,icon,esc,modal,openModal,toast,save,state:current,course:C,matches,speak,stopSpeech,image}=api;
 const bank=window.TRANSFER_PRACTICE.lessons;
 const state=()=>current();const setFor=id=>bank[id];const lessonFor=id=>C.lessons.find(l=>l.id===id);
 const plush=window.PLUSH_COLLECTION.install(api);
 function validDone(done){const result={};for(const [id,v] of Object.entries(done||{}))if(bank[id]&&v&&typeof v.at==='string'&&Number.isInteger(v.errors)&&v.errors>=0&&v.errors<=999)result[id]={at:v.at,errors:v.errors};return result;}
 function validActive(a){if(!a||!bank[a.lesson]||!Number.isInteger(a.index)||a.index<0||a.index>=bank[a.lesson].tasks.length)return null;return {lesson:a.lesson,index:a.index,draft:typeof a.draft==='string'?a.draft.slice(0,1200):'',choice:Number.isInteger(a.choice)&&a.choice>=0&&a.choice<(bank[a.lesson].tasks[a.index].options?.length||0)?a.choice:null,words:Array.isArray(a.words)?[...new Set(a.words.filter(n=>Number.isInteger(n)&&n>=0&&n<bank[a.lesson].tasks[a.index].answer.split(' ').length))]:[],passed:a.passed===true,errors:Math.min(999,Math.max(0,Math.floor(Number(a.errors)||0))),textMode:a.textMode===true,replay:a.replay===true};}
 function cards(){const s=state(),available=C.lessons.filter(l=>s.completed[l.id]);return `<div class="view library-head transfer-home"><div class="eyebrow">В другой ситуации</div><h1>Практика</h1><p>Знакомые правила, новые сообщения и задачи. Четыре задания — одна игрушка на полке.</p><a class="speaking-entry" href="#speaking"><span class="speaking-symbol">${icon('volume')}</span><div><h2>Разговорная речь</h2><p>Живой диалог по пройденным урокам</p></div>${icon('arrow')}</a><div class="transfer-meta"><span>${Object.keys(s.practiceDone).length} из ${C.lessons.length} наборов завершено</span><a class="text-link" href="#collection">Коллекция ${icon('album')}</a></div>${available.length?`<div class="transfer-grid">${available.map(l=>{const done=!!s.practiceDone[l.id],active=s.practiceActive?.lesson===l.id&&(!done||s.practiceActive.replay===true);return `<a class="transfer-card" href="#${done&&!active?'practice-complete':'transfer'}/${l.id}"><img src="${image(l)}" alt=""><div><div class="eyebrow">Эпизод ${l.number} · ${l.band}</div><h2>${esc(setFor(l.id).title)}</h2><p>${active?'Продолжить с задания '+(s.practiceActive.index+1):done?'Завершено · Повторить':'4 новых задания · игрушка в коллекцию'}</p></div>${icon(done?'check':'arrow')}</a>`;}).join('')}</div>`:`<div class="empty"><h2>Сначала — один эпизод</h2><p>После завершения урока здесь откроется практика его правил.</p><a class="secondary" href="#library">Выбрать эпизод ${icon('arrow')}</a></div>`}<section class="practice-card journal-card"><div><h2>Личный дневник</h2><p>Свои мысли на английском. Записи сохраняются без автоматической оценки.</p></div><button class="secondary" id="journal-btn">${icon('edit')} Открыть</button></section></div>`;}
 const collection=plush.collection,bindCollection=plush.bindCollection;
 function tokens(t){return t.answer.split(' ').map((word,j)=>({word,j})).sort((a,b)=>((a.j*13+7)%19)-((b.j*13+7)%19));}
 function render(id,animate=true){const s=state(),l=lessonFor(id);if(!l||!s.completed[id]){location.hash='practice';return;}if(s.practiceDone[id]&&!(s.practiceActive?.lesson===id&&s.practiceActive.replay===true)){if(s.practiceActive?.lesson===id){s.practiceActive=null;save();}location.hash='practice-complete/'+id;return;}if(s.practiceActive?.lesson!==id){s.practiceActive={lesson:id,index:0,draft:'',choice:null,words:[],passed:false,errors:0,textMode:false};save();}const a=s.practiceActive,t=bank[id].tasks[a.index],parts=tokens(t);let field=t.options?`<div class="options">${t.options.map((o,j)=>`<button class="option ${a.choice===j?'selected':''}" data-answer="${j}" aria-pressed="${a.choice===j}" ${a.passed?'disabled':''}><span class="option-index">${j+1}</span><span lang="en">${esc(o)}</span></button>`).join('')}</div>`:t.type==='order'?`<div class="sentence-tray">${a.words.map(j=>`<button class="word" data-remove-practice="${j}" ${a.passed?'disabled':''} lang="en">${esc(parts[j].word)}</button>`).join('')}</div><div class="word-bank">${parts.map((p,j)=>`<button class="word ${a.words.includes(j)?'used':''}" data-word-practice="${j}" ${a.words.includes(j)||a.passed?'disabled':''} lang="en">${esc(p.word)}</button>`).join('')}</div>`:`<label class="answer-label" for="practice-answer">${t.type==='gap'?'Одно слово':'Исправленная реплика'}</label><textarea class="response" id="practice-answer" lang="en" spellcheck="false" maxlength="1200" ${a.passed?'disabled':''}>${esc(a.draft)}</textarea>`;
 app.innerHTML=`<div class="view transfer-session"><div class="lesson-top"><a class="icon-btn" href="#practice" aria-label="Выйти из практики">${icon('back')}</a><div class="progress-track"><span style="width:${a.index/4*100}%"></span></div><span class="lesson-count">Задание ${a.index+1}/4 · ${l.band}</span></div><div class="lesson-layout"><div class="scene-image"><img src="${image(l)}" alt="${esc(C.images[l.image])}"><div class="scene-caption"><div class="eyebrow">Практика · Эпизод ${l.number}</div><h2>${esc(bank[id].title)}</h2><p>Знакомое правило в новом контексте</p></div></div><section class="exercise-panel"><div class="teacher"><img src="assets/margo.webp" alt="Аватар ведущей Марго"><div>Марго<small>Твоя ведущая</small></div></div><div class="eyebrow">Новая ситуация · без XP</div><h1>${esc(t.heading)}</h1><p class="exercise-prompt">${esc(t.prompt)}</p>${t.display?`<div class="source-excerpt" lang="en">${esc(t.display)}</div>`:''}${t.type==='listen'?`<div class="audio-card"><button class="icon-btn" id="practice-play" aria-label="Послушать сообщение">${icon('volume')}</button><div><strong>Послушай сообщение</strong><p>Ответь по смыслу, не записывай дословно.</p><div class="speech-status" id="speech-status">Нажми на значок звука</div></div><label class="audio-speed"><span class="sr-only">Скорость</span><select id="practice-speed" aria-label="Скорость воспроизведения">${[.7,.85,1,1.15,1.3].map(v=>`<option value="${v}" ${s.settings.speed===v?'selected':''}>${String(v).replace('.',',')}×</option>`).join('')}</select></label></div>${a.textMode?`<div class="source-excerpt" lang="en">${esc(t.audioText)}</div>`:'<button class="text-link" id="practice-text">Текстовый режим</button>'}`:''}<div id="practice-field">${field}</div><div id="practice-feedback" role="status" aria-live="polite">${a.passed?feedback(t):''}</div><button class="primary practice-check" id="practice-check">${a.passed?(a.index===3?'Получить игрушку':'Следующее задание'):'Проверить'} ${icon('arrow')}</button><details class="practice-rule"><summary>Правило из урока</summary><p>${esc(l.guided.cards[0].rule)}</p><a class="text-link" href="${esc(bank[id].source)}" target="_blank" rel="noopener noreferrer">Учебный источник ${icon('arrow')}</a></details></section></div></div>`;
 if(!animate)app.querySelector('.view').style.animation='none';
 const check=app.querySelector('#practice-check');const enabled=()=>check.disabled=!a.passed&&!(t.options?a.choice!==null:t.type==='order'?a.words.length===parts.length:a.draft.trim());enabled();
 app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{a.choice=+b.dataset.answer;save();app.querySelectorAll('[data-answer]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});enabled();});
 const input=app.querySelector('#practice-answer');if(input){input.oninput=()=>{a.draft=input.value;save();enabled();};input.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!check.disabled)check.click();};}
 app.querySelectorAll('[data-word-practice]').forEach(b=>b.onclick=()=>{a.words.push(+b.dataset.wordPractice);save();render(id,false);});app.querySelectorAll('[data-remove-practice]').forEach(b=>b.onclick=()=>{a.words=a.words.filter(j=>j!==+b.dataset.removePractice);save();render(id,false);});
 const play=app.querySelector('#practice-play');if(play)play.onclick=()=>speak(t.audioText);const speed=app.querySelector('#practice-speed');if(speed)speed.onchange=()=>{const playing=window.speechSynthesis?.speaking;s.settings.speed=+speed.value;stopSpeech();save();if(playing)speak(t.audioText);};const text=app.querySelector('#practice-text');if(text)text.onclick=()=>{stopSpeech();a.textMode=true;save();render(id,false);};
 check.onclick=()=>{if(a.passed){check.disabled=true;stopSpeech();if(a.index===3){if(!s.practiceDone[id])s.practiceDone[id]={at:new Date().toISOString(),errors:a.errors};s.practiceActive=null;save();location.hash='practice-complete/'+id;return;}Object.assign(a,{index:a.index+1,draft:'',choice:null,words:[],passed:false,textMode:false});save();render(id);window.scrollTo({top:0,behavior:'instant'});return;}const value=t.options?t.options[a.choice]:t.type==='order'?a.words.map(j=>parts[j].word).join(' '):a.draft;if(matches(value,t)){a.passed=true;s.activity[api.today()]=(s.activity[api.today()]||0)+1;save();render(id,false);}else{a.errors=Math.min(999,a.errors+1);save();app.querySelector('#practice-feedback').innerHTML=`<div class="feedback bad"><div class="feedback-title">Попробуй ещё раз</div><p>${esc(t.hint)}</p><button class="secondary" id="practice-hint">Разобрать ответ</button></div>`;app.querySelector('#practice-hint').onclick=()=>{app.querySelector('#practice-feedback').innerHTML=`<div class="feedback"><strong lang="en">${esc(t.answer)}</strong><p>${esc(t.explanation)}</p><p>Теперь исправь свой ответ.</p></div>`;};}};
 }
 function feedback(t){return `<div class="feedback"><div class="feedback-title">Верно</div><p>${esc(t.explanation)}</p></div>`;}
 function complete(id){if(!state().practiceDone[id]){location.hash='practice';return;}const l=lessonFor(id);app.innerHTML=`<div class="view lesson-recap"><div class="eyebrow">Практика завершена</div><h1>Новый сосед на полке</h1><p class="muted">${esc(l.ru)}</p>${plush.reward(id)}<div class="recap-buttons"><a class="primary" href="#collection">В коллекцию ${icon('arrow')}</a><button class="secondary" id="practice-repeat">Повторить ${icon('repeat')}</button><a class="text-link" href="#practice">К практике ${icon('back')}</a></div></div>`;app.querySelector('#practice-repeat').onclick=()=>{state().practiceActive={lesson:id,index:0,draft:'',choice:null,words:[],passed:false,errors:0,textMode:false,replay:true};save();location.hash='transfer/'+id;};}
 function speakingPrompt(l){const cards=l.guided?.cards||[],rules=[...new Set(cards.map(c=>c.rule).filter(r=>r&&r!=='Реплика из сцены'))],examples=cards.flatMap(c=>c.examples||[]).map(e=>e[0]).filter((v,i,a)=>a.indexOf(v)===i).slice(0,6);return `Проведи со мной разговорную практику английского по завершённому уроку приложения Afterhours.

Урок: ${l.id}, «${l.ru}». Уровень материала: ${l.band}.
Тема: ${setFor(l.id).title}.
Изученные правила:
${rules.map(r=>'— '+r).join('\n')}
Примеры конструкций из урока (не готовые ответы для тренировки):
${examples.map(e=>'— '+e).join('\n')}

Придумай новую жизненную ситуацию, отличающуюся от сцены урока. Веди со мной естественный диалог на английском, по одной реплике или вопросу за раз. Пусть мне нужно будет самому задавать вопросы, уточнять и отвечать, а не только выбирать варианты. Основной упор — изученные выше конструкции. Сначала задай короткую ситуацию по-русски и начни разговор одной английской репликой. Не показывай пример ответа заранее.
После моего ответа кратко объясняй существенную ошибку по-русски и показывай естественную исправленную формулировку. Если ошибка мешает применить изученное правило, дай исправить реплику; иначе продолжай разговор. Принимай разные правильные формулировки. Не переводи каждую реплику без просьбы и не перегружай исправлениями.
Проведи 8–12 обменов репликами, затем подведи краткий итог: что получается, что повторить и 2–3 естественные фразы из нашего разговора. Если я отвечаю текстом или ты получаешь только расшифровку, не оценивай произношение. Это отдельная практика в чате: не утверждай, что ты изменил XP или прогресс приложения.`;}
 function speakingPage(id){const l=lessonFor(id),available=C.lessons.filter(l=>state().completed[l.id]);if(id&&(!l||!state().completed[id])){location.hash='speaking';return '';}if(l){return `<div class="view profile-subpage speaking-view"><div class="subpage-heading"><a class="icon-btn" href="#speaking" aria-label="Назад к разговорной речи">${icon('back')}</a><h1>Разговорная речь</h1></div><div class="eyebrow">Эпизод ${l.number} · ${l.band}</div><h2 class="speaking-topic">${esc(setFor(id).title)}</h2><p class="speaking-intro">Скопируй сообщение в чат и начни диалог голосом или текстом.</p><label class="answer-label" for="speaking-prompt">Сообщение для чата</label><textarea class="response speaking-prompt" id="speaking-prompt" readonly>${esc(speakingPrompt(l))}</textarea><button class="primary" id="copy-speaking">${icon('book')} Скопировать сообщение</button><p class="source-note">В сообщении уже есть тема и правила урока. Экспортировать прогресс не нужно.</p></div>`;}return `<div class="view library-head speaking-view"><div class="subpage-heading"><a class="icon-btn" href="#practice" aria-label="Назад к практике">${icon('back')}</a><h1>Разговорная речь</h1></div><p class="speaking-intro">Выбери пройденный урок — подготовим тему и правила для живого диалога в чате.</p>${available.length?`<div class="transfer-grid">${available.map(l=>`<a class="transfer-card" href="#speaking/${l.id}"><img src="${image(l)}" alt=""><div><div class="eyebrow">Эпизод ${l.number} · ${l.band}</div><h2>${esc(setFor(l.id).title)}</h2><p>${esc(l.ru)}</p></div>${icon('arrow')}</a>`).join('')}</div>`:`<div class="empty"><h2>Сначала — один эпизод</h2><p>Темы для разговора открываются после завершения уроков.</p><a class="secondary" href="#library">Выбрать эпизод ${icon('arrow')}</a></div>`}</div>`;}
 function bindSpeaking(){const b=app.querySelector('#copy-speaking'),input=app.querySelector('#speaking-prompt');if(!b)return;b.onclick=async()=>{b.disabled=true;try{if(!navigator.clipboard?.writeText)throw Error('Clipboard unavailable');await navigator.clipboard.writeText(input.value);toast('Сообщение скопировано');}catch{if(input.isConnected){input.focus();input.select();let copied=false;try{copied=typeof document.execCommand==='function'&&document.execCommand('copy');}catch{}toast(copied?'Сообщение скопировано':'Выделено сообщение — скопируй его вручную');}}finally{b.disabled=false;}};}
 return {cards,collection,bindCollection,render,complete,validDone,validActive,speakingPage,bindSpeaking};
};
